// Character data only. Add/edit characters here, then refresh world.html.
// Base image paths are generated automatically from folder as:
// assets/characters/<folder>/main.webp, thumb.webp, doodle.webp, turn.webp
// Optional album slots are generated by the private Excel+ZIP importer from image file names.
// profile.basicInfo.world stores the character's 소속세계 from story-taxonomy.js.
// Set hidden: true to keep a template character out of the list.
window.CHARACTERS = [
  {
    "name": "레나",
    "en": "Lena",
    "themeColor": "#923834",
    "profile": {
      "shortIntro": "정의감이 앞서는 여우 수인 기사로, 특별한 능력 없이 검과 판단으로 약자를 지킨다.",
      "quote": "명령이 틀렸다면, 제 검은 명령이 아니라 사람을 지키겠습니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "중세",
        "race": "여우 수인",
        "job": "기사",
        "age": "20 세",
        "personality": "정의감 넘친다",
        "ability": "알려지지 않음",
        "weapon": "검",
        "height": "168 cm",
        "weight": "55 kg",
        "measurements": "90 - 60 - 92"
      }
    },
    "folder": "001-lena",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "엘리아나",
    "en": "Eliana",
    "themeColor": "#96A7C4",
    "profile": {
      "shortIntro": "자유분방한 인간 고양이탐정으로, 장난스러운 말투 뒤에 날카로운 관찰력을 숨긴다.",
      "quote": "발자국은 거짓말을 못 해요. 거짓말하는 건 늘 사람이죠.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "현대",
        "race": "인간",
        "job": "고양이탐정",
        "age": "30 ~ 39 세",
        "personality": "자유분방하다",
        "ability": "알려지지 않음",
        "weapon": "없음",
        "height": "168 cm",
        "weight": "50 kg",
        "measurements": "93 - 58 - 91"
      }
    },
    "folder": "002-eliana",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "스칼렛",
    "en": "Scarlett",
    "themeColor": "#9C2D34",
    "profile": {
      "shortIntro": "고혹적인 뱀파이어 귀족으로, 힘보다 예법과 침묵으로 상대를 압박한다.",
      "quote": "무례는 피보다 진합니다. 그래서 더 오래 얼룩지지요.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "중세",
        "race": "뱀파이어",
        "job": "귀족",
        "age": "800 세\n(추정)",
        "personality": "고혹적이다",
        "ability": "알려지지 않음",
        "weapon": "없음",
        "height": "168 cm",
        "weight": "48 kg",
        "measurements": "94 - 56 - 93"
      }
    },
    "folder": "003-scarlett",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "루시엘",
    "en": "Luciel",
    "themeColor": "#6E479E",
    "profile": {
      "shortIntro": "우아한 인간 배우로, 무대와 현실의 경계를 읽고 원하는 장면을 만들어낸다.",
      "quote": "커튼이 내려갈 때까지, 진짜 얼굴은 관객에게 맡기죠.",
      "basicInfo": {
        "gender": "여성",
        "world": "루미아",
        "genre": "현대",
        "race": "인간",
        "job": "배우",
        "age": "24 세",
        "personality": "우아하다",
        "ability": "알려지지 않음",
        "weapon": "없음",
        "height": "168 cm",
        "weight": "50 kg",
        "measurements": "92 - 56 - 91"
      }
    },
    "folder": "004-luciel",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "루나 페라노",
    "en": "Luna Ferrano",
    "themeColor": "#6F4A9E",
    "profile": {
      "shortIntro": "호전적인 늑대인간 정비공으로, 네온 아래에서 기계와 주먹을 동시에 고친다.",
      "quote": "엔진이든 사람이든, 두들겨 봐야 어디가 망가졌는지 알죠.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "사이버펑크",
        "race": "늑대인간",
        "job": "정비공",
        "age": "30 세",
        "personality": "호전적이다",
        "ability": "알려지지 않음",
        "weapon": "없음",
        "height": "168 cm",
        "weight": "58 kg",
        "measurements": "96 - 58 - 98"
      }
    },
    "folder": "005-lunaFerrano",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "엘라비야",
    "en": "Elabiah",
    "themeColor": "#B3A4BE",
    "profile": {
      "shortIntro": "섬세한 인간 시녀이자 디자이너로, 죽어도 되살아나는 몸으로 비밀스러운 궁정을 견딘다.",
      "quote": "찢어진 옷은 꿰매면 됩니다. 문제는 찢어진 충성이지요.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "중세",
        "race": "인간",
        "job": "시녀/디자이너",
        "age": "400 세",
        "personality": "섬세하다",
        "ability": "죽어도 되살아 나는 능력",
        "weapon": "없음",
        "height": "167 cm",
        "weight": "49 kg",
        "measurements": "93 - 56 - 91"
      }
    },
    "folder": "006-elabiah",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "루나",
    "en": "Luna",
    "themeColor": "#B7A2E0",
    "profile": {
      "shortIntro": "얌전한 인간 시녀로, 말수는 적지만 작은 움직임으로 궁정의 흐름을 바꾼다.",
      "quote": "저는 보이지 않는 곳을 닦습니다. 그래서 더 많은 것을 봅니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "중세",
        "race": "인간",
        "job": "시녀",
        "age": "27 세",
        "personality": "얌전하다",
        "ability": "알려지지 않음",
        "weapon": "없음",
        "height": "169 cm",
        "weight": "52 kg",
        "measurements": "92 - 56 - 91"
      }
    },
    "folder": "007-luna",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "레이나",
    "en": "Raina",
    "themeColor": "#6BAFF2",
    "profile": {
      "shortIntro": "활발하고 호기심 많은 미래 연구원으로, 수류탄을 든 채 위험한 의문을 끝까지 파고든다.",
      "quote": "터뜨리기 전에 물어볼게요. 이거, 정말 안전하다고요?",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "미래",
        "race": "인간",
        "job": "연구원",
        "age": "21 세",
        "personality": "활발하고 호기심이 많다",
        "ability": "알려지지 않음",
        "weapon": "수류탄",
        "height": "165 cm",
        "weight": "48 kg",
        "measurements": "88 - 58 - 89"
      }
    },
    "folder": "008-raina",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "취화선",
    "en": "Chihwaseon",
    "themeColor": "#4A3A67",
    "profile": {
      "shortIntro": "자유분방하고 의리 있는 무술가로, 취할수록 주먹과 마음이 더 뜨거워진다.",
      "quote": "술값은 제가 냅니다. 대신 불의한 놈은 당신이 계산하세요.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "무협",
        "race": "인간",
        "job": "무술가",
        "age": "25 세",
        "personality": "자유분방하고 의리있다",
        "ability": "술을 마시면 강해지는 능력",
        "weapon": "없음",
        "height": "168 cm",
        "weight": "53 kg",
        "measurements": "96 - 59 - 96"
      }
    },
    "folder": "009-chihwaseon",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "에리사 블랙문",
    "en": "Erissa Blackmoon",
    "themeColor": "#461766",
    "profile": {
      "shortIntro": "오만하고 똑똑한 다크엘프 매드 사이언티스트로, 폐허 속에서도 실험의 주도권을 놓지 않는다.",
      "quote": "윤리는 살아남은 뒤에 논합시다. 저는 먼저 결과를 만들겠어요.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "좀비 아포칼립스",
        "race": "다크엘프",
        "job": "매드 사이언티스트",
        "age": "200 세",
        "personality": "오만하고 똑똑하다",
        "ability": "알려지지 않음",
        "weapon": "없음",
        "height": "172 cm",
        "weight": "62 kg",
        "measurements": "120 - 60 - 95"
      }
    },
    "folder": "010-erissaBlackmoon",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "시라예 에일마리스",
    "en": "Shiraye Ailmaris",
    "themeColor": "#E11729",
    "profile": {
      "shortIntro": "응석스러운 엘프 마피아 보스로, 웃음과 저격총 사이의 거리를 마음대로 좁힌다.",
      "quote": "부탁처럼 들렸나요? 귀엽게 말했을 뿐, 명령이에요.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "호러",
        "race": "엘프",
        "job": "마피아 보스",
        "age": "170 세",
        "personality": "응석쟁이",
        "ability": "알려지지 않음",
        "weapon": "저격총",
        "height": "168 cm",
        "weight": "55 kg",
        "measurements": "115 - 56 - 92"
      }
    },
    "folder": "011-shirayeAilmaris",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "반 팔레혼",
    "en": "Van Palaeon",
    "themeColor": "#0FA383",
    "profile": {
      "shortIntro": "소심한 코볼트 판사로, 한 번 들은 말과 본 증거를 절대 잊지 않는다.",
      "quote": "기억은 겁이 많지 않습니다. 그래서 제가 대신 떨고 있죠.",
      "basicInfo": {
        "gender": "여성",
        "world": "루미아",
        "genre": "일상",
        "race": "코볼트",
        "job": "판사",
        "age": "550 세 이상",
        "personality": "소심하다",
        "ability": "한번 보거나 들은 것을 잊지 않는 능력",
        "weapon": "없음",
        "height": "164 cm",
        "weight": "49 kg",
        "measurements": "78 - 56 - 85"
      }
    },
    "folder": "012-vanPalaeon",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "에스트릴 일라스",
    "en": "Estril Illas",
    "themeColor": "#5D46AE",
    "profile": {
      "shortIntro": "쿨하고 집착 강한 다크엘프 중장보병으로, 얼굴을 바꾸어도 집념은 숨기지 못한다.",
      "quote": "가면은 바뀝니다. 하지만 겨눈 창끝은 한 번도 흔들린 적 없어요.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "다크판타지",
        "race": "다크엘프",
        "job": "중장보병",
        "age": "81 세",
        "personality": "쿨하고 집착이 심하다",
        "ability": "타인으로 변신할 수 있는 능력",
        "weapon": "창,단검",
        "height": "171 cm",
        "weight": "60 kg",
        "measurements": "115 - 56 - 94"
      }
    },
    "folder": "013-estrilIllas",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "로위나",
    "en": "Rowina",
    "themeColor": "#1770D9",
    "profile": {
      "shortIntro": "자유분방한 아수라 현자로, 물속에서도 숨 쉬며 전장의 규칙을 웃으며 뒤튼다.",
      "quote": "길이 막혔다고요? 그럼 물밑으로 가면 되죠.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "헌터물",
        "race": "아수라",
        "job": "현자",
        "age": "22 세",
        "personality": "자유분방하다",
        "ability": "물에서 숨을 쉴 수 있는 능력",
        "weapon": "마법지팡이",
        "height": "168 cm",
        "weight": "55 kg",
        "measurements": "103 - 57 - 91"
      }
    },
    "folder": "014-rowina",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "민디",
    "en": "Mindy",
    "themeColor": "#76789D",
    "profile": {
      "shortIntro": "냉혹한 유령 파이터로, 그림을 실체화해 상대가 피할 수 없는 링을 만든다.",
      "quote": "맞기 전에 보세요. 제가 그린 선 밖으로는 못 나갑니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "수사물",
        "race": "유령",
        "job": "파이터",
        "age": "85 세",
        "personality": "냉혹하다",
        "ability": "그림을 실체화 할 수 있는 능력",
        "weapon": "없음",
        "height": "170 cm",
        "weight": "측정불가",
        "measurements": "88 - 52 - 88"
      }
    },
    "folder": "015-mindy",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "세로단",
    "en": "Serothan",
    "themeColor": "#AD6ADF",
    "profile": {
      "shortIntro": "관능적인 마신족 무희로, 차가운 입김과 춤으로 제단의 시선을 붙든다.",
      "quote": "얼어붙은 숨도 리듬을 타면, 기도가 아니라 유혹이 되지요.",
      "basicInfo": {
        "gender": "여성",
        "world": "에레보스",
        "genre": "하이 판타지",
        "race": "마신족",
        "job": "무희",
        "age": "62 세",
        "personality": "관능적이다",
        "ability": "차가운 입김을 불 수 있는 능력",
        "weapon": "없음",
        "height": "178 cm",
        "weight": "68 kg",
        "measurements": "123 - 58 - 108"
      }
    },
    "folder": "016-serothan",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "나기르",
    "en": "Nagir",
    "themeColor": "#9F76C7",
    "profile": {
      "shortIntro": "신경과민한 거인 요술사로, 영원한 생과 마법서를 짊어진 채 별 사이를 떠돈다.",
      "quote": "불멸은 축복이 아닙니다. 주석이 끝나지 않는 책일 뿐.",
      "basicInfo": {
        "gender": "여성",
        "world": "아스트라",
        "genre": "SF",
        "race": "거인",
        "job": "요술사",
        "age": "39 세",
        "personality": "신경과민",
        "ability": "영원히 살 수 있는 능력",
        "weapon": "마법서",
        "height": "252 cm",
        "weight": "145 kg",
        "measurements": "138 - 76 - 128"
      }
    },
    "folder": "017-nagir",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "크리스틴 커튼",
    "en": "Kristen Cutton",
    "themeColor": "#AA834B",
    "profile": {
      "shortIntro": "재미있는 하플링 궁수로, 사물의 무게를 바꾸며 가벼운 농담처럼 위기를 넘긴다.",
      "quote": "화살이 가볍다고 얕보지 마세요. 맞는 순간 마음이 무거워질 테니까.",
      "basicInfo": {
        "gender": "여성",
        "world": "루미아",
        "genre": "멜로",
        "race": "하플링",
        "job": "궁수",
        "age": "75 세",
        "personality": "재미있다",
        "ability": "사물의 무게를 조종할 수 있는 능력",
        "weapon": "활",
        "height": "112 cm",
        "weight": "27 kg",
        "measurements": "64 - 50 - 67"
      }
    },
    "folder": "018-kristenCutton",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "시라",
    "en": "Searra",
    "themeColor": "#CDD25E",
    "profile": {
      "shortIntro": "강압적인 드레이크 교도관으로, 독과 쌍장창으로 무너진 질서를 억지로 세운다.",
      "quote": "규칙은 친절하지 않습니다. 그래서 제가 친절할 필요도 없죠.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "뉴클리어 아포칼립스",
        "race": "드레이크",
        "job": "교도관",
        "age": "62 세",
        "personality": "강압적이다",
        "ability": "독을 다룰 수 있는 능력",
        "weapon": "쌍장창",
        "height": "172 cm",
        "weight": "63 kg",
        "measurements": "118 - 58 - 98"
      }
    },
    "folder": "019-searra",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "루시아 녹스",
    "en": "Lucia Nox",
    "themeColor": "#4E1187",
    "profile": {
      "shortIntro": "용감한 마인 검투사로, 검과 방패와 음파의 함성으로 전장의 시선을 받아낸다.",
      "quote": "물러서지 마세요. 제가 먼저 소리치면, 공포가 뒤로 밀릴 겁니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "로우 판타지",
        "race": "마인",
        "job": "검투사",
        "age": "77 세",
        "personality": "용감하다",
        "ability": "큰 소리를 내서 음파를 방출하는 능력",
        "weapon": "검, 방패",
        "height": "178 cm",
        "weight": "70 kg",
        "measurements": "118 - 63 - 108"
      }
    },
    "folder": "020-luciaNox",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "bra",
      "cookmag"
    ]
  },
  {
    "name": "에시",
    "en": "Essy",
    "themeColor": "#FA3EA1",
    "profile": {
      "shortIntro": "착하고 순진한 유령 사령술사로, 여러 목숨을 가진 낫의 주인답게 죽음 앞에서도 웃는다.",
      "quote": "무섭지 않아요. 저는 돌아올 수 있으니까, 대신 당신이 살아주세요.",
      "basicInfo": {
        "gender": "여성",
        "world": "에레보스",
        "genre": "코즈믹 호러",
        "race": "유령",
        "job": "사령술사",
        "age": "46 세",
        "personality": "착하고 순진하다",
        "ability": "여러개의 목숨을 가지고 있는 능력",
        "weapon": "낫",
        "height": "172 cm",
        "weight": "측정불가",
        "measurements": "102 - 62 - 100"
      }
    },
    "folder": "021-essy",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "오투르쿠",
    "en": "Othurcu",
    "themeColor": "#F34BA2",
    "profile": {
      "shortIntro": "여유로운 용인 사제로, 죽은 자를 되살리는 힘을 신앙과 책임 사이에서 다룬다.",
      "quote": "살리는 일은 기적이 아닙니다. 그 뒤를 감당하는 일이 기적이지요.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "바이오펑크",
        "race": "용인",
        "job": "사제",
        "age": "43 세",
        "personality": "여유롭다",
        "ability": "죽은 자를 되살릴 수 있는 능력",
        "weapon": "스태프",
        "height": "183 cm",
        "weight": "106 kg",
        "measurements": "112 - 68 - 108"
      }
    },
    "folder": "022-othurcu",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "나이브",
    "en": "Nive",
    "themeColor": "#09A2F8",
    "profile": {
      "shortIntro": "장난스러운 사티로스 바드로, 미래를 엿보며 하프의 한 음으로 내일을 비튼다.",
      "quote": "방금 틀린 음이요? 내일을 미리 고쳐 친 겁니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "루미아",
        "genre": "학원물",
        "race": "사티로스",
        "job": "바드",
        "age": "21 세",
        "personality": "장난스럽다",
        "ability": "미래를 볼 수 있는 능력",
        "weapon": "하프",
        "height": "163 cm",
        "weight": "65 kg",
        "measurements": "96 - 66 - 98"
      }
    },
    "folder": "023-nive",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "아리엘",
    "en": "Ariel",
    "themeColor": "#A94532",
    "profile": {
      "shortIntro": "게으른 인어 인형술사로, 불꽃을 먹어 힘을 얻고 폐허 속 인형극을 움직인다.",
      "quote": "제가 게으른 게 아니라, 인형들이 먼저 움직이고 싶어 하는 거예요.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "포스트 아포칼립스",
        "race": "인어",
        "job": "인형술사",
        "age": "20 세",
        "personality": "게으르다",
        "ability": "불꽃을 먹으면 강해지는 능력",
        "weapon": "삼지창",
        "height": "상반신 약 88 cm,\n전체 체장 약 310 cm",
        "weight": "72 kg",
        "measurements": "82 - 57 - 88\n(꼬리기부둘레)"
      }
    },
    "folder": "024-ariel",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "가넷",
    "en": "Garnet",
    "themeColor": "#7C2B2A",
    "profile": {
      "shortIntro": "광기와 카리스마를 지닌 마수족 암살자로, 일본도 한 자루로 침묵의 길을 연다.",
      "quote": "쉿. 이름을 말하면 죽음이 길을 잃잖아.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "무협",
        "race": "마수족",
        "job": "암살자",
        "age": "33 세",
        "personality": "광기있고 카리스마 있음",
        "ability": "알려지지 않음",
        "weapon": "일본도",
        "height": "148 cm",
        "weight": "53 kg",
        "measurements": "98 - 55 - 93"
      }
    },
    "folder": "025-garnet",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "울린",
    "en": "Wulin",
    "themeColor": "#99A956",
    "profile": {
      "shortIntro": "충동적인 신수족 연금술사이자 빌런으로, 플라스크 하나로 도시의 균형을 흔든다.",
      "quote": "계산은 끝났어요. 이제 재미없는 안전장치를 깨볼 차례죠.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "다크히어로물",
        "race": "신수족",
        "job": "연금술사/빌런",
        "age": "58 세",
        "personality": "충동적이다",
        "ability": "알려지지 않음",
        "weapon": "플라스크 유리병",
        "height": "156 cm",
        "weight": "76 kg",
        "measurements": "94 - 57 - 94"
      }
    },
    "folder": "026-wulin",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "플로라 데이지베이",
    "en": "Flora Daisybay",
    "themeColor": "#A53581",
    "profile": {
      "shortIntro": "낙천적인 요정 바리스타 마법소녀로, 재채기 한 번에 인격도 사건도 뒤집힌다.",
      "quote": "주문은 달콤하게, 변신은 갑작스럽게! 에취, 이번엔 누가 나왔죠?",
      "basicInfo": {
        "gender": "여성",
        "world": "루미아",
        "genre": "마법소녀물",
        "race": "요정",
        "job": "바리스타/마법소녀",
        "age": "2000 세",
        "personality": "낙천적이다",
        "ability": "재채기하면 인격이 바뀌는 능력",
        "weapon": "마법봉",
        "height": "102 cm",
        "weight": "18 kg",
        "measurements": "55 - 43 - 58"
      }
    },
    "folder": "027-floraDaisybay",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "미브나스",
    "en": "Mibnas",
    "themeColor": "#27D3DA",
    "profile": {
      "shortIntro": "냉정한 거인 파계승으로, 염주를 굴리며 타인의 몸과 마음의 경계를 시험한다.",
      "quote": "몸을 빌릴 뿐입니다. 업보까지 대신 질 생각은 없습니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "판타지",
        "race": "거인",
        "job": "파계승",
        "age": "4000 세",
        "personality": "냉정하다",
        "ability": "타인에게 빙의할 수 있는 능력",
        "weapon": "염주",
        "height": "12 ~ 15 m",
        "weight": "약 30 ~ 40 t",
        "measurements": "900 - 540 - 880"
      }
    },
    "folder": "028-mibnas",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "앨리스",
    "en": "Alice",
    "themeColor": "#7094CF",
    "profile": {
      "shortIntro": "밝고 긍정적인 토끼 수인 리포터로, 마이크 없이도 사람들의 하루를 환하게 비춘다.",
      "quote": "나쁜 소식도 전해야죠. 대신 끝에는 희망도 꼭 찾아낼 거예요.",
      "basicInfo": {
        "gender": "여성",
        "world": "루미아",
        "genre": "현대 드라마",
        "race": "토끼 수인",
        "job": "리포터",
        "age": "23 세",
        "personality": "밝고 긍정적이다",
        "ability": "알려지지 않음",
        "weapon": "없음",
        "height": "150 cm",
        "weight": "40 kg",
        "measurements": "74 - 52 - 79"
      }
    },
    "folder": "029-alice",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "클로에",
    "en": "Chloe",
    "themeColor": "#7E6595",
    "profile": {
      "shortIntro": "귀여운 구체관절인형 메이드로, 싸울수록 강해지는 건틀릿으로 잿비를 가른다.",
      "quote": "주인님, 청소 범위에 좀비도 포함해도 될까요?",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "좀비 아포칼립스",
        "race": "구체관절인형",
        "job": "메이드",
        "age": "없음",
        "personality": "귀엽다",
        "ability": "싸울수록 강해지는 능력",
        "weapon": "건틀릿",
        "height": "162 cm",
        "weight": "39 kg",
        "measurements": "82 - 55 - 86"
      }
    },
    "folder": "030-chloe",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "키젤",
    "en": "Qeisel",
    "themeColor": "#3C7059",
    "profile": {
      "shortIntro": "감성이 풍부하고 빈틈없는 아라크네 연금술사 빌런으로, 피를 폭탄처럼 빚어낸다.",
      "quote": "아름다운 폭발엔 재료가 필요해요. 조금 아플 뿐이죠.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "하이 판타지",
        "race": "아라크네",
        "job": "연금술사/빌런",
        "age": "25 세",
        "personality": "감성이 풍부하고 빈틈이 없다",
        "ability": "피를 원하는 형태로 바꿀 수 있는 능력",
        "weapon": "폭탄",
        "height": "체고 약 190c m,\n전체 전장 약 330 cm",
        "weight": "260 kg",
        "measurements": "106 - 58 - 96\n(접합부 기준)"
      }
    },
    "folder": "031-qeisel",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "라니스",
    "en": "Rhanis",
    "themeColor": "#CCAF78",
    "profile": {
      "shortIntro": "소심한 노움 소환사로, 더블배럴샷건을 꼭 쥔 채 이세계 소환진 뒤에 숨는다.",
      "quote": "제가 부른 건 맞는데요, 책임까지 소환한 건 아니거든요?",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "이세계",
        "race": "노움",
        "job": "소환사",
        "age": "25 세",
        "personality": "소심하다",
        "ability": "알려지지 않음",
        "weapon": "더블배럴샷건",
        "height": "100 cm",
        "weight": "19 kg",
        "measurements": "58 - 47 - 60"
      }
    },
    "folder": "032-rhanis",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "미사",
    "en": "Misa",
    "themeColor": "#AA91B3",
    "profile": {
      "shortIntro": "겁 많은 나가 어부로, 낚싯대 하나로 검은 물속의 공포와 생계를 동시에 끌어올린다.",
      "quote": "큰 건 안 잡혀도 돼요. 제발 오늘은 평범한 물고기만 올라와라.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "호러",
        "race": "나가",
        "job": "어부",
        "age": "166 세",
        "personality": "겁이 많다",
        "ability": "알려지지 않음",
        "weapon": "낚시대",
        "height": "상반신 약 90 cm,\n전체 체장 약 480 cm",
        "weight": "170 kg",
        "measurements": "82 - 60 - 95\n(꼬리기부둘레)"
      }
    },
    "folder": "033-misa",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "아야",
    "en": "Aya",
    "themeColor": "#046B2D",
    "profile": {
      "shortIntro": "말 많은 염소 수인 바람술사로, 빠른 발과 리볼버로 잿바람보다 먼저 떠든다.",
      "quote": "설명할 시간이 없으니까 달리면서 설명할게요. 아, 탄은 여섯 발입니다!",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "포스트 아포칼립스",
        "race": "염소 수인",
        "job": "바람술사",
        "age": "28 세",
        "personality": "말이 많다",
        "ability": "빠르게 움직일수 있는 능력",
        "weapon": "리볼버",
        "height": "170 cm",
        "weight": "67 kg",
        "measurements": "113 - 62 - 104"
      }
    },
    "folder": "034-aya",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "타닐라 엘라민",
    "en": "Tanila Ellamin",
    "themeColor": "#A17F1E",
    "profile": {
      "shortIntro": "사심 없는 우드엘프 우주해적으로, 식물의 말을 듣고 곡사포로 별길을 연다.",
      "quote": "나무들이 항로를 속삭였어요. 그러니 포문을 여는 건 예의죠.",
      "basicInfo": {
        "gender": "여성",
        "world": "아스트라",
        "genre": "SF",
        "race": "우드엘프",
        "job": "우주해적",
        "age": "58 세",
        "personality": "사심이 없다",
        "ability": "식물의 말을 들을 수 있는 능력",
        "weapon": "곡사포",
        "height": "177 cm",
        "weight": "60 kg",
        "measurements": "108 - 58 - 93"
      }
    },
    "folder": "035-tanilaEllamin",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "셀리나",
    "en": "Celina",
    "themeColor": "#21F6CB",
    "profile": {
      "shortIntro": "어른스러운 봉제인형 방랑상인으로, 타인의 능력을 알아보며 도리깨와 거래를 함께 든다.",
      "quote": "값을 속이지 마세요. 당신 능력의 무게까지 이미 봤으니까요.",
      "basicInfo": {
        "gender": "여성",
        "world": "사프란해",
        "genre": "로우 판타지",
        "race": "봉제인형",
        "job": "방랑상인",
        "age": "없음",
        "personality": "어른스럽다",
        "ability": "타인의 능력을 알 수 있는 능력",
        "weapon": "도리깨",
        "height": "166 cm",
        "weight": "8 kg",
        "measurements": "96 - 56 - 91"
      }
    },
    "folder": "036-celina",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "sakura",
      "bra"
    ]
  },
  {
    "name": "피프 가브리엘",
    "en": "Piff Gabriel",
    "themeColor": "#8E3C92",
    "profile": {
      "shortIntro": "부주의한 임프 총독으로, 불꽃을 먹고 강해지며 해적 항구를 웃기게도 위험하게 다스린다.",
      "quote": "아차, 세금 고지서를 태웠네요. 그럼 세금도 불로 받죠!",
      "basicInfo": {
        "gender": "여성",
        "world": "사프란해",
        "genre": "해적물",
        "race": "임프",
        "job": "총독",
        "age": "94 세",
        "personality": "부주의하다",
        "ability": "불꽃을 먹으면 강해지는 능력",
        "weapon": "수리검",
        "height": "95 cm",
        "weight": "18 kg",
        "measurements": "55 - 42 - 57"
      }
    },
    "folder": "037-piffGabriel",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "프레이야",
    "en": "Freya",
    "themeColor": "#B1A7E2",
    "profile": {
      "shortIntro": "고집불통 하피 언데드사냥꾼으로, 햇빛 아래 강해지며 돌격소총을 겨눈다.",
      "quote": "해가 뜨면 숨지 마라. 그때부터 내 사냥이 시작되니까.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "영지물",
        "race": "하피",
        "job": "언데드사냥꾼",
        "age": "87 세",
        "personality": "고집불통이다",
        "ability": "햇빛에 노출되면 강해지는 능력",
        "weapon": "돌격소총",
        "height": "175 cm",
        "weight": "62 kg",
        "measurements": "95 - 54 - 96"
      }
    },
    "folder": "038-freya",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "록시",
    "en": "Roxy",
    "themeColor": "#35E323",
    "profile": {
      "shortIntro": "신중한 인간 건달로, 달빛 아래 강해지는 주먹과 너클로 느와르의 밤을 버틴다.",
      "quote": "밝은 곳에선 말로 끝냅시다. 달이 뜨면 제 주먹이 급해져서요.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "느와르",
        "race": "인간",
        "job": "건달",
        "age": "32 세",
        "personality": "신중하다",
        "ability": "달빛에 노출되면 강해지는 능력",
        "weapon": "너클",
        "height": "175 cm",
        "weight": "66 kg",
        "measurements": "105 - 60 - 98"
      }
    },
    "folder": "039-roxy",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "베가",
    "en": "Vega",
    "themeColor": "#56D1B9",
    "profile": {
      "shortIntro": "무책임한 셰이프시프터 샤먼으로, 죽으면 과거로 돌아가는 철퇴 든 방랑자다.",
      "quote": "실수요? 괜찮아요. 제가 죽으면 어차피 다시 생각할 수 있거든요.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "어반 판타지",
        "race": "셰이프시프터",
        "job": "샤먼",
        "age": "28 세",
        "personality": "무책임하다",
        "ability": "죽으면 특정 과거로 이동하는 능력",
        "weapon": "철퇴",
        "height": "172 cm",
        "weight": "60 kg",
        "measurements": "92 - 62 - 94"
      }
    },
    "folder": "040-vega",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "box",
      "beach",
      "sakura"
    ]
  },
  {
    "name": "서아",
    "en": "Seoah",
    "themeColor": "#ED1C19",
    "profile": {
      "shortIntro": "헌신적인 구체관절인형 약사로, 공간을 접어 약장을 열고 필요한 것을 꺼낸다.",
      "quote": "상처를 숨기지 마세요. 제 약장은 빈칸을 싫어하거든요.",
      "basicInfo": {
        "gender": "여성",
        "world": "루미아",
        "genre": "일상",
        "race": "구체관절인형",
        "job": "약사",
        "age": "없음",
        "personality": "헌신적인",
        "ability": "공간을 절단해 물건들을 보관할 수 있는 능력",
        "weapon": "자동권총",
        "height": "169 cm",
        "weight": "49 kg",
        "measurements": "80 - 54 - 84"
      }
    },
    "folder": "041-seoah",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "valen"
    ]
  },
  {
    "name": "리브라",
    "en": "Libra",
    "themeColor": "#A9708A",
    "profile": {
      "shortIntro": "부지런한 담피르 사서로, 책과 대도끼를 모두 다루며 궁정의 기록을 지킨다.",
      "quote": "책장을 찢으면 역사가 다칩니다. 그래서 이번엔 도끼로 대답하겠습니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "궁정물",
        "race": "담피르",
        "job": "사서",
        "age": "32 세",
        "personality": "부지런하다",
        "ability": "책을 자유자재로 조작할 수 있는 능력",
        "weapon": "대도끼",
        "height": "171 cm",
        "weight": "58 kg",
        "measurements": "96 - 58 - 93"
      }
    },
    "folder": "042-libra",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "sakura"
    ]
  },
  {
    "name": "우분",
    "en": "Wubun",
    "themeColor": "#D88A2E",
    "profile": {
      "shortIntro": "사교적인 미노타우로스 결계사로, 할버드를 세워 사람과 길의 경계를 만든다.",
      "quote": "들어오려면 인사부터 하십시오. 결계도 예의는 압니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "무협",
        "race": "미노타우로스",
        "job": "결계사",
        "age": "35 세",
        "personality": "사교적이다",
        "ability": "알려지지 않음",
        "weapon": "할버드",
        "height": "260 cm",
        "weight": "340 kg",
        "measurements": "178 - 112 - 181"
      }
    },
    "folder": "043-wubun",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "beach"
    ]
  },
  {
    "name": "세레나",
    "en": "Serena",
    "themeColor": "#4A9E87",
    "profile": {
      "shortIntro": "상냥한 백조수인 무희로, 월아삽을 들고 항해의 의식과 무대를 함께 지킨다.",
      "quote": "춤은 길을 열고, 칼날은 그 길을 지킵니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "사프란해",
        "genre": "항해물",
        "race": "백조 수인",
        "job": "무희",
        "age": "25 세",
        "personality": "상냥하다",
        "ability": "알려지지 않음",
        "weapon": "월아삽",
        "height": "169 cm",
        "weight": "52 kg",
        "measurements": "92 - 58 - 90"
      }
    },
    "folder": "044-serena",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "sakura"
    ]
  },
  {
    "name": "타키온",
    "en": "Tachyon",
    "themeColor": "#2B78D3",
    "profile": {
      "shortIntro": "자신감 넘치는 다크엘프 드래곤라이더로, 갈고리창과 하늘길로 히어로의 전선을 연다.",
      "quote": "아래에서 보니 높아 보이죠? 위에선 두려움도 작아집니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "히어로물",
        "race": "다크엘프",
        "job": "드래곤라이더",
        "age": "38 세",
        "personality": "자신감 있다",
        "ability": "알려지지 않음",
        "weapon": "갈고리창",
        "height": "178 cm",
        "weight": "63 kg",
        "measurements": "88 - 60 - 90"
      }
    },
    "folder": "045-tachyon",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "글루미",
    "en": "Gloomy",
    "themeColor": "#9C85BA",
    "profile": {
      "shortIntro": "우울한 캇파 사진작가로, 독반지와 카메라로 범죄 도시의 젖은 진실을 남긴다.",
      "quote": "웃지 않아도 됩니다. 진짜 얼굴은 셔터가 알아서 찾아내요.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "범죄물",
        "race": "캇파",
        "job": "사진작가",
        "age": "785 세",
        "personality": "우울한",
        "ability": "알려지지 않음",
        "weapon": "독반지",
        "height": "167 cm",
        "weight": "53 kg",
        "measurements": "83 - 58 - 87"
      }
    },
    "folder": "046-gloomy",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "beach"
    ]
  },
  {
    "name": "러스트",
    "en": "Rust",
    "themeColor": "#ADBDA9",
    "profile": {
      "shortIntro": "고요한 골렘 메카닉으로, 용암 같은 힘과 병 하나로 별먼지 기계를 고친다.",
      "quote": "달궈진 쇠는 거짓말을 못 합니다. 식기 전에 손봐야죠.",
      "basicInfo": {
        "gender": "여성",
        "world": "아스트라",
        "genre": "스페이스 웨스턴",
        "race": "골렘",
        "job": "메카닉",
        "age": "62 세",
        "personality": "고요한",
        "ability": "용암을 다룰 수 있는 능력",
        "weapon": "병",
        "height": "168 cm",
        "weight": "70 kg",
        "measurements": "86 - 61 - 90"
      }
    },
    "folder": "047-rust",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "니리",
    "en": "Niri",
    "themeColor": "#906B41",
    "profile": {
      "shortIntro": "영적인 나비 메이드로, 괴물화하는 몸과 탄토를 붙들고 감염된 저택을 청소한다.",
      "quote": "무서워하지 마세요. 괴물이 되어도 앞치마는 더럽히지 않겠습니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "감염병 아포칼립스",
        "race": "나비족",
        "job": "메이드",
        "age": "32 세",
        "personality": "영적인",
        "ability": "신체를 괴물화 할 수 있는 능력",
        "weapon": "탄토",
        "height": "203 cm",
        "weight": "82 kg",
        "measurements": "112 - 61 - 105"
      }
    },
    "folder": "048-niri",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "maid"
    ]
  },
  {
    "name": "시시",
    "en": "Xi-Xi",
    "themeColor": "#355CF1",
    "profile": {
      "shortIntro": "소심한 강시 로봇공학자로, 그림자 이동과 핸드캐넌으로 낡은 도시의 기계를 깨운다.",
      "quote": "저, 저는 그림자 쪽이 편해요. 거기선 심장 소리도 덜 들리거든요.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "호러",
        "race": "강시",
        "job": "로봇공학자",
        "age": "25 세",
        "personality": "소심한",
        "ability": "그림자를 통해 이동할 수 있는 능력",
        "weapon": "핸드캐넌",
        "height": "169 cm",
        "weight": "54 kg",
        "measurements": "86 - 57 - 88"
      }
    },
    "folder": "049-xi-xi",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "니나",
    "en": "Nina",
    "themeColor": "#2BCBC3",
    "profile": {
      "shortIntro": "사려 깊은 봉제인형 수도사로, 꿈을 조작하며 마체테로 검댕 수도원의 악몽을 자른다.",
      "quote": "나쁜 꿈은 꾸어도 됩니다. 제가 깨어날 길을 꿰매둘게요.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "디젤펑크",
        "race": "봉제인형",
        "job": "수도사",
        "age": "없음",
        "personality": "사려 깊은",
        "ability": "꿈을 조작할 수 있는 능력",
        "weapon": "마체테",
        "height": "152 cm",
        "weight": "26 kg",
        "measurements": "78 - 56 - 82"
      }
    },
    "folder": "050-nina",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "초아",
    "en": "Choa",
    "themeColor": "#45DC24",
    "profile": {
      "shortIntro": "자유분방한 미라 예언자로, 망각을 일으키는 차크람으로 잊힌 길을 연다.",
      "quote": "잊어도 괜찮아요. 중요한 운명은 다시 상처처럼 떠오르니까.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "무협",
        "race": "미라",
        "job": "예언자",
        "age": "29 세",
        "personality": "자유분방한",
        "ability": "망각을 유발할 수 있는 능력",
        "weapon": "차크람",
        "height": "166 cm",
        "weight": "49 kg",
        "measurements": "84 - 58 - 86"
      }
    },
    "folder": "051-choa",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "로건",
    "en": "Logan",
    "themeColor": "#8B7D11",
    "profile": {
      "shortIntro": "강인한 늑대수인 경찰관으로, 화승총보다 먼저 동네의 평화를 지키는 발걸음을 뗀다.",
      "quote": "큰 소리 내기 전에 한 번만 더 생각하세요. 저는 총보다 빨리 뜁니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "루미아",
        "genre": "일상",
        "race": "늑대 수인",
        "job": "경찰관",
        "age": "25 세",
        "personality": "강인한",
        "ability": "알려지지 않음",
        "weapon": "화승총",
        "height": "168 cm",
        "weight": "57 kg",
        "measurements": "92 - 58 - 94"
      }
    },
    "folder": "052-logan",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "조이",
    "en": "Joy",
    "themeColor": "#98EF12",
    "profile": {
      "shortIntro": "다정한 엔트 운동선수로, 작은 폭풍을 두르고 폐허의 결승선까지 사람을 이끈다.",
      "quote": "느려 보여도 뿌리는 깊습니다. 끝까지 같이 가죠.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "포스트 아포칼립스",
        "race": "엔트",
        "job": "운동선수",
        "age": "68 세",
        "personality": "다정한",
        "ability": "자신 주변에 작은 폭풍을 만들 수 있는 능력",
        "weapon": "검",
        "height": "168 cm",
        "weight": "52 kg",
        "measurements": "80 - 57 - 83"
      }
    },
    "folder": "053-joy",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "미아",
    "en": "Mia",
    "themeColor": "#15D927",
    "profile": {
      "shortIntro": "수줍은 슬라임 사신으로, 불운을 부여하는 낫을 품고 항로의 끝을 조심스레 안내한다.",
      "quote": "죄송해요. 제가 지나가면 일이 꼬이지만, 길은 잃지 않게 해드릴게요.",
      "basicInfo": {
        "gender": "여성",
        "world": "사프란해",
        "genre": "실크로드판타지",
        "race": "슬라임",
        "job": "사신",
        "age": "26 세",
        "personality": "수줍은",
        "ability": "상대에게 불운을 부여할 수 있는 능력",
        "weapon": "낫",
        "height": "98 cm",
        "weight": "10 kg",
        "measurements": "51 - 42 -54"
      }
    },
    "folder": "054-mia",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "가은",
    "en": "GaEun",
    "themeColor": "#1F8857",
    "profile": {
      "shortIntro": "착한 리치 교사로, 인형과 와키자시를 다루며 동양 서당의 아이들을 지킨다.",
      "quote": "죽었다고 배움이 끝나진 않아요. 자, 오늘 숙제부터 봅시다.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "동양판타지",
        "race": "리치",
        "job": "교사",
        "age": "외형 39세 / 실제 180세",
        "personality": "착한",
        "ability": "인형을 움직일 수 있는 능력",
        "weapon": "와키자시",
        "height": "202 cm",
        "weight": "72 kg",
        "measurements": "98 - 67 - 100"
      }
    },
    "folder": "055-gaeun",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "실비아",
    "en": "Sylvia",
    "themeColor": "#2A4C4F",
    "profile": {
      "shortIntro": "예민한 문엘프 요리사로, 닿기만 해도 독을 주입하는 손과 식칼을 조심스럽게 쓴다.",
      "quote": "제 음식은 정직합니다. 독이 든 건 접시가 아니라 손끝이에요.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "영지물",
        "race": "문엘프",
        "job": "요리사",
        "age": "97 세",
        "personality": "예민한",
        "ability": "상대에게 닿으면 독을 주입하는 능력",
        "weapon": "식칼",
        "height": "166 cm",
        "weight": "48 kg",
        "measurements": "84 - 55 - 86"
      }
    },
    "folder": "056-sylvia",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "비비안",
    "en": "Vivian",
    "themeColor": "#637115",
    "profile": {
      "shortIntro": "차가운 천인 탐정으로, 폭풍과 쌍도끼를 두르고 사막 항로의 단서를 추적한다.",
      "quote": "바람은 증거를 지우죠. 그래서 저는 폭풍째로 붙잡습니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "사프란해",
        "genre": "실크로드판타지",
        "race": "천인",
        "job": "탐정",
        "age": "34 세",
        "personality": "차가운",
        "ability": "자신 주변에 작은 폭풍을 만들 수 있는 능력",
        "weapon": "쌍도끼",
        "height": "178 cm",
        "weight": "65 kg",
        "measurements": "95 - 60 - 97"
      }
    },
    "folder": "057-vivian",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "디아나",
    "en": "Diana",
    "themeColor": "#A1DF56",
    "profile": {
      "shortIntro": "계획적인 나가 플로리스트로, 몸속 독을 힘으로 바꾸며 타로 카드처럼 사건을 배열한다.",
      "quote": "꽃말은 친절하지만 독은 솔직하죠. 어느 쪽으로 들으실래요?",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "첩보",
        "race": "나가",
        "job": "플로리스트",
        "age": "35 세",
        "personality": "계획적인",
        "ability": "몸속의 독을 힘으로 바꿀 수 있는 능력",
        "weapon": "타로 카드",
        "height": "상반신 약 108cm,\n전체 체장 약 690 cm",
        "weight": "235 kg",
        "measurements": "101 - 63 -  96\n(꼬리기부둘레)"
      }
    },
    "folder": "058-diana",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "리제",
    "en": "Lize",
    "themeColor": "#DDD529",
    "profile": {
      "shortIntro": "침착한 구울 현상금사냥꾼으로, 빛을 굴절해 모습을 감추고 갈고리로 표적을 낚는다.",
      "quote": "보이지 않는다고 사라진 건 아닙니다. 현상금도, 저도.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "게임판타지",
        "race": "구울",
        "job": "현상금사냥꾼",
        "age": "34 세",
        "personality": "침착한",
        "ability": "빛을 굴절시켜 모습을 감출 수 있는 능력",
        "weapon": "갈고리",
        "height": "180 cm",
        "weight": "58 kg",
        "measurements": "88 - 58 - 92"
      }
    },
    "folder": "059-lize",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "그레이스",
    "en": "Grace",
    "themeColor": "#7A6670",
    "profile": {
      "shortIntro": "자신감 있는 인간 사제로, 몸을 연기처럼 흩어 스태프 끝의 선협 기운을 흘린다.",
      "quote": "형태가 흩어져도 뜻은 남습니다. 그러니 물러서세요.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "선협",
        "race": "인간",
        "job": "사제",
        "age": "29 세",
        "personality": "자신감 있는",
        "ability": "몸을 연기처럼 흩어지게 할 수 있는 능력",
        "weapon": "스태프",
        "height": "181 cm",
        "weight": "63 kg",
        "measurements": "92 - 61 - 94"
      }
    },
    "folder": "060-grace",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "엘레나",
    "en": "Elena",
    "themeColor": "#0F6E6E",
    "profile": {
      "shortIntro": "꼼꼼한 안드로이드 바텐더로, 레이피어보다 정확한 손놀림으로 네온의 잔을 따른다.",
      "quote": "주문은 기록했습니다. 취향과 거짓말까지 함께요.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "바이오펑크",
        "race": "안드로이드",
        "job": "바텐더",
        "age": "450 세",
        "personality": "꼼꼼한",
        "ability": "알려지지 않음",
        "weapon": "레이피어",
        "height": "176 cm",
        "weight": "68 kg",
        "measurements": "94 - 59 -94"
      }
    },
    "folder": "061-elena",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "이네스",
    "en": "Ines",
    "themeColor": "#939FDC",
    "profile": {
      "shortIntro": "당찬 유령 탐정으로, 독과 노다치를 들고 궁정물의 초상 뒤 진실을 벤다.",
      "quote": "죽었다고 조용히 있으란 법은 없죠. 저는 아직 사건 중입니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "궁정물",
        "race": "유령",
        "job": "탐정",
        "age": "33 세",
        "personality": "당찬",
        "ability": "독을 다룰 수 있는 능력",
        "weapon": "노다치",
        "height": "175 cm",
        "weight": "57 kg",
        "measurements": "96 - 58 -96"
      }
    },
    "folder": "062-ines",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "비앙카",
    "en": "Bianca",
    "themeColor": "#5A32FF",
    "profile": {
      "shortIntro": "불안한 인간 왕족으로, 괴력과 워픽을 억누르며 눈왕관의 무게를 견딘다.",
      "quote": "왕관이 무거운 게 아니라, 제가 부술까 봐 무서운 겁니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "설원판타지",
        "race": "인간",
        "job": "왕족",
        "age": "32 세",
        "personality": "불안한",
        "ability": "괴력을 발휘할 수 있는 능력",
        "weapon": "워픽",
        "height": "168 cm",
        "weight": "56 kg",
        "measurements": "91 - 56 - 90"
      }
    },
    "folder": "063-bianca",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "japanFestival"
    ]
  },
  {
    "name": "티나",
    "en": "Tina",
    "themeColor": "#783D52",
    "profile": {
      "shortIntro": "명랑한 요정 스캐빈저로, 공격 에너지를 흡수하고 쌍단검으로 모래 속 보물을 캐낸다.",
      "quote": "위험한 건 제가 받을게요. 반짝이는 건 같이 나눠요!",
      "basicInfo": {
        "gender": "여성",
        "world": "사프란해",
        "genre": "실크로드판타지",
        "race": "요정",
        "job": "스캐빈저",
        "age": "29 세",
        "personality": "명랑한",
        "ability": "상대의 공격 에너지를 흡수할 수 있는 능력",
        "weapon": "쌍단검",
        "height": "148 cm",
        "weight": "39 kg",
        "measurements": "76 - 54 - 79"
      }
    },
    "folder": "064-tina",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "아이리스",
    "en": "Iris",
    "themeColor": "#06D291",
    "profile": {
      "shortIntro": "까칠한 쥐 수인 도사로, 비녀 하나로 동방 골목의 잡귀와 사람을 동시에 꾸짖는다.",
      "quote": "예의 없이 굴면 귀신도 사람도 똑같이 혼납니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "동양판타지",
        "race": "쥐 수인",
        "job": "도사",
        "age": "233 세",
        "personality": "까칠한",
        "ability": "알려지지 않음",
        "weapon": "비녀",
        "height": "168 cm",
        "weight": "53 kg",
        "measurements": "96 - 56 - 89"
      }
    },
    "folder": "065-iris",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "에이미",
    "en": "Amy",
    "themeColor": "#B0BC19",
    "profile": {
      "shortIntro": "불안한 유령 경비병으로, 무기 없이 밤비 내리는 순찰구역의 이름표를 지킨다.",
      "quote": "제가 무서운 게 아닙니다. 제가 지키는 문 너머가 무서운 거죠.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "유령수사물",
        "race": "유령",
        "job": "경비병",
        "age": "21 세",
        "personality": "불안한",
        "ability": "알려지지 않음",
        "weapon": "없음",
        "height": "158 cm",
        "weight": "43 kg",
        "measurements": "78 - 56 - 82"
      }
    },
    "folder": "066-amy",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "연화",
    "en": "LianHua",
    "themeColor": "#3C5FDE",
    "profile": {
      "shortIntro": "착한 마신족 낭인으로, 염주를 굴리며 선협의 길 위에서 자기 악명을 거둔다.",
      "quote": "마신이라 불러도 좋습니다. 오늘 벨 사람은 그 이름이 아닙니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "선협",
        "race": "마신족",
        "job": "낭인",
        "age": "20 세",
        "personality": "착한",
        "ability": "알려지지 않음",
        "weapon": "염주",
        "height": "168 cm",
        "weight": "52 kg",
        "measurements": "98 - 58 -92"
      }
    },
    "folder": "067-lianHua",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "가온",
    "en": "Gaon",
    "themeColor": "#D01DB7",
    "profile": {
      "shortIntro": "대담한 양 수인 사냥꾼으로, 상대 능력을 약화시키며 감염지대의 곡월도를 휘두른다.",
      "quote": "네 힘이 무섭다고? 그럼 잠깐 빌려서 꺼버리면 되지.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "감염병 아포칼립스",
        "race": "양 수인",
        "job": "사냥꾼",
        "age": "31 세",
        "personality": "대담한",
        "ability": "상대의 능력을 짧은 시간 동안 약화시키거나 무효화할 수 있는 능력",
        "weapon": "곡월도",
        "height": "173 cm",
        "weight": "62 kg",
        "measurements": "105 - 60 - 94"
      }
    },
    "folder": "068-gaon",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "테이라",
    "en": "Theira",
    "themeColor": "#11F0AA",
    "profile": {
      "shortIntro": "수수께끼 같은 타이탄 고행사제로, 괴물화하는 몸과 성표로 신화의 고통을 짊어진다.",
      "quote": "기도는 작아도 됩니다. 거신의 그림자는 이미 충분히 크니까요.",
      "basicInfo": {
        "gender": "여성",
        "world": "에레보스",
        "genre": "신화판타지",
        "race": "타이탄",
        "job": "고행사제",
        "age": "2500 세",
        "personality": "수수께끼 같은",
        "ability": "신체를 괴물화 할 수 있는 능력",
        "weapon": "홀리 심볼",
        "height": "13.5 m",
        "weight": "약 42 t",
        "measurements": "880 - 520 - 910"
      }
    },
    "folder": "069-theira",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "셀비",
    "en": "Selby",
    "themeColor": "#5EE466",
    "profile": {
      "shortIntro": "고집 센 아수라 마피아 보스로, 청각을 마비시키고 대형망치로 침묵을 명령한다.",
      "quote": "시끄러운 충성은 필요 없어. 내 앞에선 조용히 무릎 꿇어.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "판타지",
        "race": "아수라",
        "job": "마피아 보스",
        "age": "36 세",
        "personality": "고집 센",
        "ability": "상대의 청각을 일시적으로 마비시키는 능력",
        "weapon": "대형망치",
        "height": "174 cm",
        "weight": "62 kg",
        "measurements": "101 - 62 - 96"
      }
    },
    "folder": "070-selby",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "가일",
    "en": "Guile",
    "themeColor": "#E0DD49",
    "profile": {
      "shortIntro": "대담한 곰 수인 총잡이로, 나노펑크 골목에서 쿠크리를 빼 들고 먼저 돌진한다.",
      "quote": "총알이 떨어지면? 그때부터는 가까워질 시간이지.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "나노펑크",
        "race": "곰 수인",
        "job": "총잡이",
        "age": "28 세",
        "personality": "대담한",
        "ability": "알려지지 않음",
        "weapon": "쿠크리",
        "height": "178 cm",
        "weight": "81 kg",
        "measurements": "108 - 72 - 104"
      }
    },
    "folder": "071-guile",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "스카",
    "en": "Scar",
    "themeColor": "#C0C288",
    "profile": {
      "shortIntro": "반항적인 늑대인간 집사로, 식칼과 저녁 식탁 사이에서 예의와 본능을 다룬다.",
      "quote": "주인님, 오늘 만찬은 얌전하게 끝내겠습니다. 아마도요.",
      "basicInfo": {
        "gender": "여성",
        "world": "루미아",
        "genre": "요리물",
        "race": "늑대인간",
        "job": "집사",
        "age": "34 세",
        "personality": "반항적인",
        "ability": "알려지지 않음",
        "weapon": "식칼",
        "height": "175 cm",
        "weight": "64 kg",
        "measurements": "96 - 61 - 98"
      }
    },
    "folder": "072-scar",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "라비",
    "en": "Rabi",
    "themeColor": "#BC4874",
    "profile": {
      "shortIntro": "논리적인 토끼 수인 첩자로, 작은 생물로 변해 사이버 도시의 허점을 파고든다.",
      "quote": "큰 문은 잠겨 있죠. 그래서 저는 작은 틈을 계산합니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "사이버펑크",
        "race": "토끼 수인",
        "job": "첩자",
        "age": "28 세",
        "personality": "논리적인",
        "ability": "작은 생물로 변신할 수 있는 능력",
        "weapon": "메이스",
        "height": "169 cm",
        "weight": "52 kg",
        "measurements": "82 - 57 - 86"
      }
    },
    "folder": "073-rabi",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "로나",
    "en": "Rona",
    "themeColor": "#00801E",
    "profile": {
      "shortIntro": "논리적인 하프엘프 외과의로, 되감는 치유와 독반지를 냉정한 수술대 위에 올린다.",
      "quote": "상처를 되돌릴 수는 있습니다. 선택까지 무효로 만들 순 없지만요.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "에코펑크",
        "race": "하프엘프",
        "job": "외과의",
        "age": "36 세",
        "personality": "논리적인",
        "ability": "상처를 입기 전 상태로 몸을 되돌릴 수 있는 능력",
        "weapon": "독반지",
        "height": "172 cm",
        "weight": "58 kg",
        "measurements": "94 - 60 - 93"
      }
    },
    "folder": "074-rona",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "아니카",
    "en": "Anika",
    "themeColor": "#94DC09",
    "profile": {
      "shortIntro": "비밀스러운 구울 밀수꾼으로, 수리검을 숨기고 감염 항로의 금지 화물을 옮긴다.",
      "quote": "상자를 열지 마세요. 내용물보다 비밀이 더 위험합니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "감염병 아포칼립스",
        "race": "구울",
        "job": "밀수꾼",
        "age": "32 세",
        "personality": "비밀스러운",
        "ability": "알려지지 않음",
        "weapon": "수리검",
        "height": "173 cm",
        "weight": "54 kg",
        "measurements": "88 - 56 - 89"
      }
    },
    "folder": "075-anika",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "가르카",
    "en": "Garka",
    "themeColor": "#75185C",
    "profile": {
      "shortIntro": "이성적인 트롤 재단사로, 별돛과 옷감 사이에서 쌍검처럼 정확한 재단선을 긋는다.",
      "quote": "옷은 몸을 속이지 않습니다. 그래서 저는 먼저 치수를 믿죠.",
      "basicInfo": {
        "gender": "여성",
        "world": "아스트라",
        "genre": "스페이스 오페라",
        "race": "트롤",
        "job": "재단사",
        "age": "524 세",
        "personality": "이성적인",
        "ability": "알려지지 않음",
        "weapon": "쌍검",
        "height": "208 cm",
        "weight": "116 kg",
        "measurements": "126 - 86 - 124"
      }
    },
    "folder": "076-garka",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "젤라",
    "en": "Zella",
    "themeColor": "#5C8479",
    "profile": {
      "shortIntro": "오만한 와이트 배틀메이지로, 햇빛 아래 강해지는 주술검을 들고 승리를 선언한다.",
      "quote": "그림자가 길수록 좋습니다. 곧 태양이 제 편이라는 뜻이니까.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "게임판타지",
        "race": "와이트",
        "job": "배틀메이지",
        "age": "25 세",
        "personality": "오만한",
        "ability": "햇빛에 노출되면 강해지는 능력",
        "weapon": "주술검",
        "height": "174 cm",
        "weight": "60 kg",
        "measurements": "94 - 58 - 91"
      }
    },
    "folder": "077-zella",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "나이아",
    "en": "Naia",
    "themeColor": "#65A7B4",
    "profile": {
      "shortIntro": "예민한 루살카 대장장이로, 햇빛을 힘으로 삼아 솔라펑크의 합성궁을 벼린다.",
      "quote": "불꽃이 아니라 햇살로 달굽니다. 그래서 제 활은 숨을 쉽니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "솔라펑크",
        "race": "루살카",
        "job": "대장장이",
        "age": "32 세",
        "personality": "예민한",
        "ability": "햇빛에 노출되면 강해지는 능력",
        "weapon": "합성궁",
        "height": "174 cm",
        "weight": "54 kg",
        "measurements": "84 - 58 - 87"
      }
    },
    "folder": "078-naia",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "모이라",
    "en": "Moira",
    "themeColor": "#2910A5",
    "profile": {
      "shortIntro": "도도한 마신족 언데드사냥꾼으로, 광선의 눈과 쌍월도로 궁정의 어둠을 벤다.",
      "quote": "죽은 자가 예의를 잊었군요. 그럼 제가 다시 눕혀드리죠.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "궁정물",
        "race": "마신족",
        "job": "언데드사냥꾼",
        "age": "37 세",
        "personality": "도도한",
        "ability": "눈에서 광선을 쏠 수 있는 능력",
        "weapon": "쌍월도",
        "height": "174 cm",
        "weight": "61 kg",
        "measurements": "102 - 58 - 96"
      }
    },
    "folder": "079-moira",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "티스카",
    "en": "Tiska",
    "themeColor": "#883F56",
    "profile": {
      "shortIntro": "우유부단한 사마귀 수인 리포터로, 장소의 기억을 읽고 전투우산 아래 진실을 망설인다.",
      "quote": "보긴 봤는데요, 말해도 되는 기억인지는 아직 모르겠어요.",
      "basicInfo": {
        "gender": "여성",
        "world": "아스트라",
        "genre": "우주개척물",
        "race": "사마귀 수인",
        "job": "리포터",
        "age": "20 세",
        "personality": "우유부단한",
        "ability": "장소에 남은 기억을 읽을 수 있는 능력",
        "weapon": "전투우산",
        "height": "170 cm",
        "weight": "53 kg",
        "measurements": "83 - 58 - 86"
      }
    },
    "folder": "080-tiska",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "카밀라",
    "en": "Carmilla",
    "themeColor": "#883F56",
    "profile": {
      "shortIntro": "서늘한 박쥐 수인 마법소녀로, 방패를 들고 호러 도시의 새벽을 막아선다.",
      "quote": "빛나는 주문은 없어요. 그래도 막아낼 수는 있습니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "호러",
        "race": "박쥐 수인",
        "job": "마법소녀",
        "age": "38 세",
        "personality": "서늘한",
        "ability": "알려지지 않음",
        "weapon": "방패",
        "height": "173 cm",
        "weight": "56 kg",
        "measurements": "87 - 58 - 91"
      }
    },
    "folder": "081-carmilla",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "에이다",
    "en": "Ada",
    "themeColor": "#12BB89",
    "profile": {
      "shortIntro": "강인한 오토마톤 인공지능학자로, 에너지 방어막과 전기톱으로 밀리터리SF 전선을 버틴다.",
      "quote": "계산 결과, 후퇴보다 방어가 더 효율적입니다. 그러니 제가 섭니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "밀리터리SF",
        "race": "오토마톤",
        "job": "인공지능학자",
        "age": "없음",
        "personality": "강인한",
        "ability": "에너지를 방어막으로 바꿀 수 있는 능력",
        "weapon": "전기톱",
        "height": "172 cm",
        "weight": "64 kg",
        "measurements": "92 - 58 - 90"
      }
    },
    "folder": "082-ada",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "시요",
    "en": "Siyo",
    "themeColor": "#478DE6",
    "profile": {
      "shortIntro": "소심한 드라이어드 식신술사로, 장궁을 들고 산의 숨과 작은 식신을 부른다.",
      "quote": "저, 저는 약하지만… 이 숲은 저보다 오래 기억해요.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "소드앤소서리",
        "race": "드라이어드",
        "job": "식신술사",
        "age": "21 세",
        "personality": "소심한",
        "ability": "알려지지 않음",
        "weapon": "장궁",
        "height": "165 cm",
        "weight": "49 kg",
        "measurements": "84 - 56 - 87"
      }
    },
    "folder": "083-siyo",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "샤드",
    "en": "Shard",
    "themeColor": "#259FCD",
    "profile": {
      "shortIntro": "불안한 구체관절인형 생존자로, 투명해지는 몸과 파워피스트로 좀비 폐허를 지나간다.",
      "quote": "안 보인다고 안전한 건 아니에요. 그래도 오늘은 그걸 믿을래요.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "좀비 아포칼립스",
        "race": "구체관절인형",
        "job": "생존자",
        "age": "없음",
        "personality": "불안한",
        "ability": "몸을 투명하게 만들 수 있는 능력",
        "weapon": "파워피스트",
        "height": "168 cm",
        "weight": "48 kg",
        "measurements": "78 - 55 - 82"
      }
    },
    "folder": "084-shard",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "노바",
    "en": "Nova",
    "themeColor": "#E64B4F",
    "profile": {
      "shortIntro": "고요한 골렘 로봇공학자로, 빛을 흡수해 힘으로 바꾸며 볼라를 던진다.",
      "quote": "빛은 사라지지 않습니다. 제 안에서 다른 일로 바뀔 뿐.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "아톰펑크",
        "race": "골렘",
        "job": "로봇공학자",
        "age": "22 세",
        "personality": "고요한",
        "ability": "자신에게 닿은 빛을 흡수해 힘으로 바꾸는 능력",
        "weapon": "볼라",
        "height": "170 cm",
        "weight": "59 kg",
        "measurements": "88 - 57 - 90"
      }
    },
    "folder": "085-nova",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "포코",
    "en": "Poko",
    "themeColor": "#751999",
    "profile": {
      "shortIntro": "질투심 많은 너구리 수인 대학생으로, 어둠 속 기척을 지우고 방패 뒤에서 버틴다.",
      "quote": "나도 할 수 있어요. 아무도 못 봤을 뿐이지.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "사이버펑크",
        "race": "너구리 수인",
        "job": "대학생",
        "age": "22 세",
        "personality": "질투심 많은",
        "ability": "어두운 곳에서 기척을 지울 수 있는 능력",
        "weapon": "방패",
        "height": "158 cm",
        "weight": "46 kg",
        "measurements": "78 - 56 - 82"
      }
    },
    "folder": "086-poko",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "시아",
    "en": "Sia",
    "themeColor": "#1CF2AF",
    "profile": {
      "shortIntro": "책임감 강한 캇파 현자로, 냉기로 상대 움직임을 둔하게 만들고 권총으로 범죄를 멈춘다.",
      "quote": "빠른 악의도 식으면 느려집니다. 그때 말로 끝내죠.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "범죄물",
        "race": "캇파",
        "job": "현자",
        "age": "32 세",
        "personality": "책임감 강한",
        "ability": "상대의 움직임을 냉기로 둔하게 만드는 능력",
        "weapon": "권총",
        "height": "168 cm",
        "weight": "54 kg",
        "measurements": "84 - 59 - 88"
      }
    },
    "folder": "087-sia",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "율",
    "en": "Yul",
    "themeColor": "#399839",
    "profile": {
      "shortIntro": "논리적인 강시 용병으로, 금지 행동을 선포하고 주술검으로 로우 판타지의 규칙을 세운다.",
      "quote": "하지 말라고 정했으면, 당신 몸도 그 명령을 따를 겁니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "로우 판타지",
        "race": "강시",
        "job": "용병",
        "age": "39 세",
        "personality": "논리적인",
        "ability": "자신이 정한 금지 행동을 상대가 하지 못하게 하는 능력",
        "weapon": "주술검",
        "height": "169 cm",
        "weight": "49 kg",
        "measurements": "78 - 55 - 84"
      }
    },
    "folder": "088-yul",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "엘리시아",
    "en": "Elysia",
    "themeColor": "#435624",
    "profile": {
      "shortIntro": "상냥한 설녀 첩자로, 체력이 낮아질수록 빨라지는 검으로 하이 판타지의 눈길을 가른다.",
      "quote": "괜찮아요. 저는 지칠수록 더 멀리 갈 수 있으니까.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "하이 판타지",
        "race": "설녀",
        "job": "첩자",
        "age": "36 세",
        "personality": "상냥한",
        "ability": "체력이 낮아질수록 움직임이 빨라지는 능력",
        "weapon": "검",
        "height": "168 cm",
        "weight": "52 kg",
        "measurements": "84 - 58 - 86"
      }
    },
    "folder": "089-elysia",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "리아",
    "en": "Lia",
    "themeColor": "#953E16",
    "profile": {
      "shortIntro": "부지런한 오니 마도공학자로, 말한 내용을 잠시 현실로 만들고 암살검을 숨긴다.",
      "quote": "입으로 만든 기계는 오래 못 갑니다. 그래서 빨리 끝내야 해요.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "오컬트",
        "race": "오니",
        "job": "마도공학자",
        "age": "25 세",
        "personality": "부지런한",
        "ability": "말한 내용을 잠시 현실로 만들 수 있는 능력",
        "weapon": "암살검",
        "height": "174 cm",
        "weight": "62 kg",
        "measurements": "103 - 58 - 97"
      }
    },
    "folder": "090-lia",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "움브라",
    "en": "Umbra",
    "themeColor": "#893FE2",
    "profile": {
      "shortIntro": "우울한 문엘프 교도관으로, 암기를 품고 비 오는 법정의 침묵을 관리한다.",
      "quote": "죄수보다 오래 갇혀 있는 건, 판결을 들은 사람들입니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "법정물",
        "race": "문엘프",
        "job": "교도관",
        "age": "35 세",
        "personality": "우울한",
        "ability": "알려지지 않음",
        "weapon": "암기",
        "height": "172 cm",
        "weight": "58 kg",
        "measurements": "94 - 63 - 96"
      }
    },
    "folder": "091-umbra",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "오피시나",
    "en": "Officina",
    "themeColor": "#B51594",
    "profile": {
      "shortIntro": "조심스러운 만드라고라 요괴사냥꾼으로, 불꽃과 방울로 이세계의 숲을 깨운다.",
      "quote": "방울이 세 번 울리면 도망치세요. 네 번째는 제가 들을 차례입니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "이세계",
        "race": "만드라고라",
        "job": "요괴사냥꾼",
        "age": "32 세",
        "personality": "조심스러운",
        "ability": "손끝에서 불꽃을 만들어낼 수 있는 능력",
        "weapon": "방울",
        "height": "167 cm",
        "weight": "52 kg",
        "measurements": "94 - 57 - 89"
      }
    },
    "folder": "092-officina",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "이슬라",
    "en": "Yslra",
    "themeColor": "#803A7E",
    "profile": {
      "shortIntro": "결단력 있는 마인 몬스터헌터로, 길어지는 싸움 속 약점을 읽고 파워피스트를 꽂는다.",
      "quote": "오래 버틸수록 좋습니다. 당신의 빈틈이 더 또렷해지니까.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "설원판타지",
        "race": "마인",
        "job": "몬스터헌터",
        "age": "33 세",
        "personality": "결단력 있는",
        "ability": "싸움이 길어질수록 상대의 약점을 파악하는 능력",
        "weapon": "파워피스트",
        "height": "172 cm",
        "weight": "58 kg",
        "measurements": "101 - 58 - 93"
      }
    },
    "folder": "093-yslra",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "카스티엘라",
    "en": "Castiella",
    "themeColor": "#8AE087",
    "profile": {
      "shortIntro": "자상한 타천사 인형술사로, 검과 인형을 데리고 해양판타지의 항구를 건넌다.",
      "quote": "망가진 인형도 안아주면 다시 손을 뻗습니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "사프란해",
        "genre": "해양판타지",
        "race": "타천사",
        "job": "인형술사",
        "age": "39 세",
        "personality": "자상한",
        "ability": "알려지지 않음",
        "weapon": "검",
        "height": "169 cm",
        "weight": "52 kg",
        "measurements": "83 - 58 - 88"
      }
    },
    "folder": "094-castiella",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "키마에라",
    "en": "Kymayra",
    "themeColor": "#A0B6D4",
    "profile": {
      "shortIntro": "집착적인 인간 소방관으로, 동물의 능력을 빌리고 독침을 감추며 전장을 구조한다.",
      "quote": "살릴 수 있다면 무엇이든 빌립니다. 짐승의 발톱이라도요.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "밀리터리SF",
        "race": "인간",
        "job": "소방관",
        "age": "20 세",
        "personality": "집착적인",
        "ability": "동물의 신체 능력을 잠시 얻을 수 있는 능력",
        "weapon": "독침",
        "height": "168 cm",
        "weight": "54 kg",
        "measurements": "84 - 58 - 88"
      }
    },
    "folder": "095-kymayra",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "토르카",
    "en": "torqa",
    "themeColor": "#025847",
    "profile": {
      "shortIntro": "비밀스러운 곰 수인 표사로, 활을 메고 무협 산길의 짐과 약속을 끝까지 옮긴다.",
      "quote": "짐을 잃으면 돈을 잃지만, 약속을 잃으면 길을 잃습니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "무협",
        "race": "곰 수인",
        "job": "표사",
        "age": "31 세",
        "personality": "비밀스러운",
        "ability": "알려지지 않음",
        "weapon": "활",
        "height": "167 cm",
        "weight": "56 kg",
        "measurements": "90 - 60 - 91"
      }
    },
    "folder": "096-torqa",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "아멜리스",
    "en": "Amelys",
    "themeColor": "#213C55",
    "profile": {
      "shortIntro": "다정한 엘프 사령술사로, 금속을 조종하고 단궁을 당겨 설원전장의 죽음을 위로한다.",
      "quote": "죽은 이의 갑옷도 아직 따뜻한 이름을 기억합니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "설원판타지",
        "race": "엘프",
        "job": "사령술사",
        "age": "32 세",
        "personality": "다정한",
        "ability": "금속을 조종할 수 있는 능력",
        "weapon": "단궁",
        "height": "172 cm",
        "weight": "56 kg",
        "measurements": "92 - 59 - 89"
      }
    },
    "folder": "097-amelys",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "드레드나",
    "en": "Dreadna",
    "themeColor": "#AF7237",
    "profile": {
      "shortIntro": "자상한 다크드워프 마왕으로, 존재감을 지우고 단검 하나로 신화의 왕좌에서 내려온다.",
      "quote": "무서워하지 마라. 오늘은 네 그림자가 아니라 내가 숨겠다.",
      "basicInfo": {
        "gender": "여성",
        "world": "에레보스",
        "genre": "신화판타지",
        "race": "다크드워프",
        "job": "마왕",
        "age": "33 세",
        "personality": "자상한",
        "ability": "자신의 존재감을 지울 수 있는 능력",
        "weapon": "단검",
        "height": "142 cm",
        "weight": "47 kg",
        "measurements": "99 - 52 - 88"
      }
    },
    "folder": "098-dreadna",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "자히라",
    "en": "Zahyra",
    "themeColor": "#F72212",
    "profile": {
      "shortIntro": "용감한 좀비 폐허탐색자로, 빛을 만들어내고 장궁으로 중동풍 폐허의 길을 밝힌다.",
      "quote": "어둠이 길을 삼켜도 괜찮아. 내가 먼저 불을 켤게.",
      "basicInfo": {
        "gender": "여성",
        "world": "사프란해",
        "genre": "중동판타지",
        "race": "좀비",
        "job": "폐허탐색자",
        "age": "23 세",
        "personality": "용감한",
        "ability": "빛을 만들어낼 수 있는 능력",
        "weapon": "장궁",
        "height": "168 cm",
        "weight": "53 kg",
        "measurements": "88 - 58 - 86"
      }
    },
    "folder": "099-zahyra",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "바레타",
    "en": "Barretha",
    "themeColor": "#941F96",
    "profile": {
      "shortIntro": "서늘한 거인 왕족으로, 개틀링건의 무게만큼 디스토피아 왕좌의 명령을 안다.",
      "quote": "왕관이 작아 보입니까? 그래서 총구를 크게 만들었습니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "디스토피아SF",
        "race": "거인",
        "job": "왕족",
        "age": "99 세",
        "personality": "서늘한",
        "ability": "알려지지 않음",
        "weapon": "개틀링건",
        "height": "740 cm",
        "weight": "5.4 t",
        "measurements": "520 - 390 - 560"
      }
    },
    "folder": "100-barretha",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "묘화",
    "en": "MyoHwa",
    "themeColor": "#8CDCA3",
    "profile": {
      "shortIntro": "꼼꼼한 여우 수인 요괴사냥꾼으로, 어둠으로 시야를 막고 낫으로 생존의 길을 벤다.",
      "quote": "눈을 가리면 괴물도 길을 잃죠. 저는 그때 베면 됩니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "생존물",
        "race": "여우 수인",
        "job": "요괴사냥꾼",
        "age": "43 세",
        "personality": "꼼꼼한",
        "ability": "어둠으로 상대의 시야를 막을 수 있는 능력",
        "weapon": "낫",
        "height": "176 cm",
        "weight": "62 kg",
        "measurements": "96 - 58 - 94"
      }
    },
    "folder": "101-myohwa",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "아테니아",
    "en": "Athenia",
    "themeColor": "#CA0354",
    "profile": {
      "shortIntro": "몽환적인 올빼미 수인 인챈터로, 어둠과 전기 채찍으로 고대 유적의 잠을 깨운다.",
      "quote": "밤은 사라진 지식의 잉크예요. 저는 그걸 다시 읽을 뿐입니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "에레보스",
        "genre": "고대문명판타지",
        "race": "올빼미 수인",
        "job": "인챈터",
        "age": "22 세",
        "personality": "몽환적인",
        "ability": "어둠을 만들어낼 수 있는 능력",
        "weapon": "전기 채찍",
        "height": "168 cm",
        "weight": "58 kg",
        "measurements": "96 - 58 - 91"
      }
    },
    "folder": "102-athenia",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "실렉스",
    "en": "Silex",
    "themeColor": "#D7F2EB",
    "profile": {
      "shortIntro": "결단력 있는 사이보그 원소술사로, EMP 폐허에서 전자기기를 망가뜨리고 창을 든다.",
      "quote": "꺼져야 들리는 소리도 있습니다. 지금부터는 제 차례예요.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "EMP 아포칼립스",
        "race": "사이보그",
        "job": "원소술사",
        "age": "25 세",
        "personality": "결단력 있는",
        "ability": "주변 전자기기를 망가뜨릴 수 있는 능력",
        "weapon": "창,수정구",
        "height": "168 cm",
        "weight": "60 kg",
        "measurements": "85 - 61 - 90"
      }
    },
    "folder": "103-silex",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "가비아",
    "en": "Gavia",
    "themeColor": "#DB1FEA",
    "profile": {
      "shortIntro": "뻔뻔한 악어 수인 사냥꾼으로, 진동으로 물체를 부수고 쌍도끼로 폐허를 헤친다.",
      "quote": "튼튼하다고요? 그럼 어디가 울리는지 먼저 물어봅시다.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "EMP 아포칼립스",
        "race": "악어 수인",
        "job": "사냥꾼",
        "age": "32 세",
        "personality": "뻔뻔한",
        "ability": "진동으로 물체를 부술 수 있는 능력",
        "weapon": "쌍도끼",
        "height": "178 cm",
        "weight": "58 kg",
        "measurements": "100 - 58 - 94"
      }
    },
    "folder": "104-gavia",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "누벨",
    "en": "Nouvel",
    "themeColor": "#AE6676",
    "profile": {
      "shortIntro": "얌전한 인간 만화가로, 그림을 실체화하고 투척카드로 미래 도시의 상상을 꺼낸다.",
      "quote": "말로는 부끄러워서요. 대신 제가 그린 게 대답해줄 거예요.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "미래",
        "race": "인간",
        "job": "만화가",
        "age": "26 세",
        "personality": "얌전한",
        "ability": "그림을 실체화 할 수 있는 능력",
        "weapon": "투척카드",
        "height": "163 cm",
        "weight": "48 kg",
        "measurements": "82 - 56 - 84"
      }
    },
    "folder": "105-nouvel",
    "albumKeys": [
      "magazine",
      "sketch",
      "cookmag"
    ]
  },
  {
    "name": "제니트",
    "en": "Zenith",
    "themeColor": "#7C5CB1",
    "profile": {
      "shortIntro": "초연한 표범 수인 언데드사냥꾼으로, 전기로 질주하고 수류탄으로 오컬트의 밤을 끝낸다.",
      "quote": "죽음이 따라온다면, 제가 더 빠르게 달리면 됩니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "오컬트",
        "race": "표범 수인",
        "job": "언데드사냥꾼",
        "age": "25 세",
        "personality": "초연한",
        "ability": "전기를 이용해 빠르게 움직일 수 있는 능력",
        "weapon": "수류탄",
        "height": "170 cm",
        "weight": "53 kg",
        "measurements": "81 - 57 - 87"
      }
    },
    "folder": "106-zenith",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "오르솔라",
    "en": "Ursola",
    "themeColor": "#6ECDAC",
    "profile": {
      "shortIntro": "욕심 많은 문어 수인 기사로, 자신의 그림자로 상대를 붙잡고 갈고리로 끌어당긴다.",
      "quote": "도망갈 수 있다고 생각했나요? 제 그림자는 손이 많습니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "하이 판타지",
        "race": "문어 수인",
        "job": "기사",
        "age": "39 세",
        "personality": "욕심 많은",
        "ability": "자신의 그림자로 상대를 붙잡을 수 있는 능력",
        "weapon": "갈고리",
        "height": "176 cm",
        "weight": "71 kg",
        "measurements": "106 - 68 - 112"
      }
    },
    "folder": "107-ursola",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "미라벨",
    "en": "Mirabel",
    "themeColor": "#962EE1",
    "profile": {
      "shortIntro": "내성적인 구울 형사로, 땅의 진동을 읽고 검으로 다크판타지의 증거를 찾는다.",
      "quote": "말하지 않아도 됩니다. 발밑은 이미 대답하고 있으니까요.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "다크판타지",
        "race": "구울",
        "job": "형사",
        "age": "29 세",
        "personality": "내성적인",
        "ability": "땅의 진동으로 주변 움직임을 감지하는 능력",
        "weapon": "검",
        "height": "167 cm",
        "weight": "55 kg",
        "measurements": "93 - 59 - 90"
      }
    },
    "folder": "108-mirabel",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "베스퍼",
    "en": "Vesper",
    "themeColor": "#656795",
    "profile": {
      "shortIntro": "우울한 엘프 퇴마사로, 죽은 자의 힘을 잠시 빌리고 머신 피스톨로 어둠을 밀어낸다.",
      "quote": "미안합니다. 당신의 힘을 빌려서라도, 산 사람을 지켜야 해요.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "호러",
        "race": "엘프",
        "job": "퇴마사",
        "age": "27 세",
        "personality": "우울한",
        "ability": "죽은 자의 힘을 잠시 빌릴 수 있는 능력",
        "weapon": "머신 피스톨",
        "height": "168 cm",
        "weight": "51 kg",
        "measurements": "84 - 58 - 87"
      }
    },
    "folder": "109-vesper",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "벨로아",
    "en": "Velour",
    "themeColor": "#B4833F",
    "profile": {
      "shortIntro": "강인한 토끼 수인 로봇공학자로, 돌풍과 유탄발사기로 메카 전장의 고장을 고친다.",
      "quote": "나사가 빠졌다고요? 괜찮아요. 적부터 날려버리고 조립하죠.",
      "basicInfo": {
        "gender": "여자",
        "world": "코어벨트",
        "genre": "메카물",
        "race": "토끼 수인",
        "job": "로봇공학자",
        "age": "24 세",
        "personality": "강인한",
        "ability": "돌풍으로 상대를 밀어낼 수 있는 능력",
        "weapon": "유탄발사기",
        "height": "173 cm",
        "weight": "59 kg",
        "measurements": "92 - 61 - 93"
      }
    },
    "folder": "110-velour",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "아나크리스",
    "en": "Anachris",
    "themeColor": "#09F2A0",
    "profile": {
      "shortIntro": "이기적인 켄타우로스 조련사로, 같은 하루를 반복하며 신화의 마구간에서 패배를 고친다.",
      "quote": "오늘도 다시 시작이군요. 이번엔 말부터 믿어보겠습니다.",
      "basicInfo": {
        "gender": "여자",
        "world": "에레보스",
        "genre": "신화판타지",
        "race": "켄타우로스",
        "job": "조련사",
        "age": "24 세",
        "personality": "이기적인",
        "ability": "같은 하루를 반복할 수 있는 능력",
        "weapon": "일본도",
        "height": "220 cm",
        "weight": "520 kg",
        "measurements": "88 - 61 - 90\n(접합부 기준)"
      }
    },
    "folder": "111-anachris",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "련",
    "en": "Ryeon",
    "themeColor": "#1F8F28",
    "profile": {
      "shortIntro": "수줍은 엘프 바리스타로, 클로를 숨기고 현대 카페의 작은 친절을 조심스럽게 건넨다.",
      "quote": "단맛은 조금만 넣었어요. 마음까지 들킬까 봐요.",
      "basicInfo": {
        "gender": "여자",
        "world": "루미아",
        "genre": "현대",
        "race": "엘프",
        "job": "바리스타",
        "age": "31 세",
        "personality": "수줍은",
        "ability": "알려지지 않음",
        "weapon": "클로",
        "height": "166 cm",
        "weight": "51 kg",
        "measurements": "82 - 60 - 86"
      }
    },
    "folder": "112-ryeon",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "릭시아",
    "en": "Lixia",
    "themeColor": "#71F7F4",
    "profile": {
      "shortIntro": "소심한 엔트 결계사로, 빛분신과 단검으로 괴수 앞의 작은 선을 지킨다.",
      "quote": "저 선만 넘지 못하게 하면 돼요. 저라도, 할 수 있어요.",
      "basicInfo": {
        "gender": "여자",
        "world": "게이트폴",
        "genre": "괴수물",
        "race": "엔트",
        "job": "결계사",
        "age": "25 세",
        "personality": "소심한",
        "ability": "빛으로 만든 분신을 만들어낼 수 있는 능력",
        "weapon": "단검",
        "height": "164 cm",
        "weight": "48 kg",
        "measurements": "80 - 58 - 86"
      }
    },
    "folder": "113-lixia",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "이브리스",
    "en": "Yvris",
    "themeColor": "#C75A72",
    "profile": {
      "shortIntro": "내성적인 벌 수인 댄서로, 차가운 입김과 마체테로 증기항의 무대를 얼린다.",
      "quote": "박수는 괜찮아요. 너무 가까이 오지만 말아주세요.",
      "basicInfo": {
        "gender": "여자",
        "world": "사프란해",
        "genre": "스팀펑크",
        "race": "벌 수인",
        "job": "댄서",
        "age": "35 세",
        "personality": "내성적인",
        "ability": "차가운 입김을 불 수 있는 능력",
        "weapon": "마체테",
        "height": "165 cm",
        "weight": "53 kg",
        "measurements": "82 - 59 - 87"
      }
    },
    "folder": "114-yvris",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "휘소",
    "en": "Hwiso",
    "themeColor": "#1C5CF8",
    "profile": {
      "shortIntro": "꼼꼼한 골렘 매니저로, 비녀검을 품고 현대 드라마의 일정과 사람을 동시에 관리한다.",
      "quote": "분 단위로 늦으면 마음도 밀립니다. 그러니 지금 움직이죠.",
      "basicInfo": {
        "gender": "여자",
        "world": "루미아",
        "genre": "현대 드라마",
        "race": "골렘",
        "job": "매니저",
        "age": "30 세",
        "personality": "꼼꼼한",
        "ability": "알려지지 않음",
        "weapon": "비녀검",
        "height": "168 cm",
        "weight": "55 kg",
        "measurements": "88 - 61 - 91"
      }
    },
    "folder": "115-hwiso",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "릭스",
    "en": "Ryx",
    "themeColor": "#8CA8B0",
    "profile": {
      "shortIntro": "비밀스러운 용인 결계사로, 그림자로 변하고 전투삽으로 코즈믹 호러의 경계를 묻는다.",
      "quote": "보이지 않는 문은 땅속에도 있습니다. 제가 파서 닫겠습니다.",
      "basicInfo": {
        "gender": "여자",
        "world": "에레보스",
        "genre": "코즈믹 호러",
        "race": "용인",
        "job": "결계사",
        "age": "23 세",
        "personality": "비밀스러운",
        "ability": "그림자로 변신할 수 있는 능력",
        "weapon": "전투삽",
        "height": "167 cm",
        "weight": "58 kg",
        "measurements": "82 - 58 - 86"
      }
    },
    "folder": "116-ryx",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "니르바",
    "en": "Nyrva",
    "themeColor": "#682F86",
    "profile": {
      "shortIntro": "헌신적인 티플링 사신으로, 위치를 바꾸는 힘과 플라즈마건으로 죽음의 순서를 흔든다.",
      "quote": "그 자리는 제가 대신 서겠습니다. 아직 당신 차례가 아니니까.",
      "basicInfo": {
        "gender": "여자",
        "world": "에레보스",
        "genre": "코즈믹 호러",
        "race": "티플링",
        "job": "사신",
        "age": "22 세",
        "personality": "헌신적인",
        "ability": "자신과 상대의 위치를 바꿀 수 있는 능력",
        "weapon": "플라즈마건",
        "height": "164 cm",
        "weight": "49 kg",
        "measurements": "83 - 58 - 86"
      }
    },
    "folder": "117-nyrva",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "네리사",
    "en": "Nerissa",
    "themeColor": "#17D53E",
    "profile": {
      "shortIntro": "카리스마 있는 정령 해적으로, 몸을 가볍게 띄우고 사브르로 항해의 하늘까지 점령한다.",
      "quote": "바다가 막으면 하늘로 가면 되지. 해적에게 길은 너무 많아.",
      "basicInfo": {
        "gender": "여자",
        "world": "사프란해",
        "genre": "항해물",
        "race": "정령",
        "job": "해적",
        "age": "24 세",
        "personality": "카리스마 있는",
        "ability": "자신의 몸을 가볍게 만들어 높이 뛰는 능력",
        "weapon": "사브르",
        "height": "172 cm",
        "weight": "52 kg",
        "measurements": "88 - 59 - 91"
      }
    },
    "folder": "118-nerissa",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "로엔",
    "en": "Loen",
    "themeColor": "#DC03DC",
    "profile": {
      "shortIntro": "상냥한 여우 수인 메카닉으로, 레이저 소총보다 따뜻한 손으로 소프트SF의 기계를 살린다.",
      "quote": "고장난 건 버리지 않아요. 조금만 들어보면 다시 움직일 이유가 있거든요.",
      "basicInfo": {
        "gender": "여자",
        "world": "코어벨트",
        "genre": "소프트SF",
        "race": "여우 수인",
        "job": "메카닉",
        "age": "21 세",
        "personality": "상냥한",
        "ability": "알려지지 않음",
        "weapon": "레이저 소총",
        "height": "166 cm",
        "weight": "53 kg",
        "measurements": "87 - 58 - 88"
      }
    },
    "folder": "119-loen",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "신시아",
    "en": "Cynthia",
    "themeColor": "#E2D5C5",
    "profile": {
      "shortIntro": "논리적인 인간 가수로, 마이크 하나로 아이돌 무대의 감정과 계산을 동시에 맞춘다.",
      "quote": "감동은 우연이 아니에요. 정확한 박자 위에서 가장 크게 빛나죠.",
      "basicInfo": {
        "gender": "여자",
        "world": "루미아",
        "genre": "아이돌물",
        "race": "인간",
        "job": "가수",
        "age": "26 세",
        "personality": "논리적인",
        "ability": "알려지지 않음",
        "weapon": "마이크",
        "height": "172 cm",
        "weight": "56 kg",
        "measurements": "92 - 56 - 92"
      }
    },
    "folder": "120-cynthia",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "카르마",
    "en": "Karma",
    "themeColor": "#3EBDEE",
    "profile": {
      "shortIntro": "예의 바른 마신족 집사로, 방패와 피해 전가 능력으로 주인의 상처까지 대신 정리한다.",
      "quote": "상처는 제가 받겠습니다. 돌려줄 곳은 이미 정해 두었으니까요.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "마피아물",
        "race": "마신족",
        "job": "집사",
        "age": "24 세",
        "personality": "지적인",
        "ability": "받은 피해를 다른 대상에게 옮길 수 있는 능력",
        "weapon": "방패",
        "height": "168 cm",
        "weight": "52 kg",
        "measurements": "86 - 58 - 88"
      }
    },
    "folder": "121-karma",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "모나",
    "en": "Mona",
    "themeColor": "#F8DCA9",
    "profile": {
      "shortIntro": "다정한 클론 넷러너로, 특별한 이능 없이 해킹 실력과 온기로 가상도시의 길을 연다.",
      "quote": "코드는 차가워도, 그 안에 남은 사람까지 차갑게 대할 필요는 없잖아요.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "가상현실물",
        "race": "클론",
        "job": "넷러너",
        "age": "35 세",
        "personality": "다정한",
        "ability": "알려지지 않음",
        "weapon": "스태프",
        "height": "169 cm",
        "weight": "59 kg",
        "measurements": "101 - 61 - 94"
      }
    },
    "folder": "122-mona",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "리터",
    "en": "Lethar",
    "themeColor": "#8147D1",
    "profile": {
      "shortIntro": "비관적인 담피르 마녀로, 판관필 끝에서 다른 차원의 물건을 꺼내며 금기의 선을 재단한다.",
      "quote": "꺼낼 수 있다고 해서, 이 세계에 있어도 된다는 뜻은 아니에요.",
      "basicInfo": {
        "gender": "여성",
        "world": "에레보스",
        "genre": "호러",
        "race": "담피르",
        "job": "마녀",
        "age": "29 세",
        "personality": "비관적인",
        "ability": "다른 차원의 물건을 꺼낼 수 있는 능력",
        "weapon": "판관필",
        "height": "168 cm",
        "weight": "52 kg",
        "measurements": "82 - 58 - 88"
      }
    },
    "folder": "123-lethar",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "만티스",
    "en": "Mantis",
    "themeColor": "#D49FB6",
    "profile": {
      "shortIntro": "계획적인 사마귀 수인 총잡이로, 리볼버와 목소리 탈취 능력으로 결투장을 침묵시킨다.",
      "quote": "말은 지금 해두세요. 총성이 울리면 침묵도 제 무기가 됩니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "아스트라",
        "genre": "스페이스 웨스턴",
        "race": "사마귀 수인",
        "job": "총잡이",
        "age": "28 세",
        "personality": "계획적인",
        "ability": "상대의 목소리를 빼앗을 수 있는 능력",
        "weapon": "리볼버",
        "height": "168 cm",
        "weight": "58 kg",
        "measurements": "92 - 60 - 95"
      }
    },
    "folder": "124-mantis",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "미카지",
    "en": "Mikazi",
    "themeColor": "#955013",
    "profile": {
      "shortIntro": "조심스러운 마도기계인 사이버닌자로, 네온 속 달빛을 계산하며 식칼을 숨긴다.",
      "quote": "서두르지 않습니다. 달빛이 닿는 순간, 승산은 제 쪽으로 기울 테니까요.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "SF",
        "race": "마도기계인",
        "job": "사이버닌자",
        "age": "26 세",
        "personality": "조심스러운",
        "ability": "달빛에 노출되면 강해지는 능력",
        "weapon": "식칼",
        "height": "174 cm",
        "weight": "72 kg",
        "measurements": "88 - 59 - 93"
      }
    },
    "folder": "125-mikazi",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "마린",
    "en": "Marine",
    "themeColor": "#61EF1F",
    "profile": {
      "shortIntro": "장엄한 문엘프 변신술사로, 물처럼 흐르는 몸과 기계활로 괴수의 빈틈을 사냥한다.",
      "quote": "붙잡았다고 생각했나요? 물은 손아귀보다 사냥감의 발자국을 더 잘 기억합니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "몬스터헌터물",
        "race": "문엘프",
        "job": "변신술사",
        "age": "178 세",
        "personality": "승부욕 강한, 장엄한",
        "ability": "몸을 물처럼 흐르게 만들 수 있는 능력",
        "weapon": "기계활",
        "height": "178 cm",
        "weight": "62 kg",
        "measurements": "105 - 57 - 94"
      }
    },
    "folder": "126-marine",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "에스메",
    "en": "Esme",
    "themeColor": "#6C4DB1",
    "profile": {
      "shortIntro": "까칠한 말 수인 용병으로, 특별한 이능 없이 쿠나이와 품격으로 계약을 완수한다.",
      "quote": "싼 의뢰는 받지 않습니다. 제 침묵도 제 칼날도 값이 있거든요.",
      "basicInfo": {
        "gender": "여성",
        "world": "아스트라",
        "genre": "스페이스 웨스턴",
        "race": "말 수인",
        "job": "용병",
        "age": "36 세",
        "personality": "까칠한, 고급스러운",
        "ability": "알려지지 않음",
        "weapon": "쿠나이",
        "height": "174 cm",
        "weight": "59 kg",
        "measurements": "92 - 61 - 91"
      }
    },
    "folder": "127-esme",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "라비니아",
    "en": "Lavinia",
    "themeColor": "#CCA481",
    "profile": {
      "shortIntro": "도발적인 늑대 수인 소환사로, 햇빛 아래 강해진 몸과 팔치온으로 전장을 몰아붙인다.",
      "quote": "그림자에 숨어보세요. 해가 뜨면 제가 아니라 제 소환수가 먼저 찾을 테니까요.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "이능력배틀물",
        "race": "늑대 수인",
        "job": "소환사",
        "age": "35 세",
        "personality": "예민한, 날카로운",
        "ability": "햇빛에 노출되면 강해지는 능력",
        "weapon": "팔치온",
        "height": "168 cm",
        "weight": "55 kg",
        "measurements": "88 - 61 - 89"
      }
    },
    "folder": "128-lavinia",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "가람",
    "en": "Garam",
    "themeColor": "#3EDC60",
    "profile": {
      "shortIntro": "싱그러운 호랑이 수인 검객으로, 특별한 이능 없이 환도와 헌신으로 앞길을 연다.",
      "quote": "재주는 없어도 물러서지는 않습니다. 그러니 제 칼끝 뒤에 서세요.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "사극판타지",
        "race": "호랑이 수인",
        "job": "검객",
        "age": "24 세",
        "personality": "헌신적인, 싱그러운",
        "ability": "알려지지 않음",
        "weapon": "환도",
        "height": "154 cm",
        "weight": "43 kg",
        "measurements": "75 - 54 - 82"
      }
    },
    "folder": "129-garam",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "다프네",
    "en": "Daphne",
    "themeColor": "#036C5F",
    "profile": {
      "shortIntro": "능글맞은 만드라고라 연구원으로, 반드시 돌아오는 차크람처럼 실험과 책임을 되돌려 받는다.",
      "quote": "던졌으면 돌아와야죠. 차크람도, 표본도, 제 실험비도요.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "바이오펑크",
        "race": "만드라고라",
        "job": "연구원",
        "age": "154 세",
        "personality": "즉흥적인, 폭발적인",
        "ability": "자신이 던진 물체를 반드시 되돌아오게 하는 능력",
        "weapon": "차크람",
        "height": "173 cm",
        "weight": "54 kg",
        "measurements": "112 - 64 - 98"
      }
    },
    "folder": "130-daphne",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "사비아",
    "en": "Sabia",
    "themeColor": "#0B2432",
    "profile": {
      "shortIntro": "활발한 노움 모래술사로, 레버액션 소총과 맞을수록 단단해지는 몸으로 항로를 누빈다.",
      "quote": "한 발 더 쏴봐요. 제 갑옷은 겁먹는 대신 더 단단해지거든요!",
      "basicInfo": {
        "gender": "여성",
        "world": "사프란해",
        "genre": "탐험물",
        "race": "노움",
        "job": "모래술사",
        "age": "32 세",
        "personality": "자신감 있는, 생기 있는",
        "ability": "공격을 받을수록 방어력이 강해지는 능력",
        "weapon": "레버액션 소총",
        "height": "105 cm",
        "weight": "22 kg",
        "measurements": "63 - 47 - 66"
      }
    },
    "folder": "131-sabia",
    "albumKeys": [
      "magazine"
    ]
  },
  {
    "name": "셀레스트",
    "en": "Celeste",
    "themeColor": "#3DDFE1",
    "profile": {
      "shortIntro": "참을성 있는 수정인 검투사로, 특별한 이능 없이 건틀릿과 단단한 몸으로 투기장을 버틴다.",
      "quote": "서두르지 마세요. 금이 가는 쪽이 저인지 당신인지 보면 되니까요.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "소프트SF",
        "race": "수정인",
        "job": "검투사",
        "age": "39 세",
        "personality": "참을성 있는, 요염한",
        "ability": "알려지지 않음",
        "weapon": "건틀릿",
        "height": "176 cm",
        "weight": "62 kg",
        "measurements": "94 - 60 - 96"
      }
    },
    "folder": "132-celeste",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "에델린",
    "en": "Edeline",
    "themeColor": "#A005FD",
    "profile": {
      "shortIntro": "잔잔한 구체관절인형 병사로, 멈춘 시간과 곡사포의 궤적으로 전장의 생존을 만든다.",
      "quote": "잠깐이면 됩니다. 제가 멈춘 그 순간에 누군가는 살아 돌아가니까요.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "전쟁물",
        "race": "구체관절인형",
        "job": "병사",
        "age": "없음",
        "personality": "희생적인, 잔잔한",
        "ability": "시간을 멈출 수 있는 능력",
        "weapon": "곡사포",
        "height": "178 cm",
        "weight": "62 kg",
        "measurements": "112 - 56 - 94"
      }
    },
    "folder": "133-edeline",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "브리자",
    "en": "Vryza",
    "themeColor": "#ECC404",
    "profile": {
      "shortIntro": "활발한 오니 암살자로, 불길 속에서도 타지 않는 몸과 사슬로 목표를 끌어낸다.",
      "quote": "불이라면 더 크게 질러봐! 그 안으로 뛰어드는 암살자도 필요하잖아?",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "동양판타지",
        "race": "오니",
        "job": "암살자",
        "age": "121 세",
        "personality": "활발한, 압도적인",
        "ability": "불에 타지 않는 능력",
        "weapon": "사슬",
        "height": "172 cm",
        "weight": "64 kg",
        "measurements": "96 - 62 - 98"
      }
    },
    "folder": "134-vryza",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "키락사",
    "en": "Kyraxa",
    "themeColor": "#370C73",
    "profile": {
      "shortIntro": "퇴폐적인 전갈 수인 파이터로, 건틀릿과 기억 읽기 능력으로 상대의 거짓을 찌른다.",
      "quote": "거짓말은 입으로만 하는 게 아니야. 네 기억이 먼저 배신했거든.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "이능력배틀물",
        "race": "전갈 수인",
        "job": "파이터",
        "age": "33 세",
        "personality": "불신이 강한, 퇴폐적인",
        "ability": "상대의 기억을 읽을 수 있는 능력",
        "weapon": "건틀릿",
        "height": "171 cm",
        "weight": "58 kg",
        "measurements": "96 - 58 - 95"
      }
    },
    "folder": "135-kyraxa",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "시아란",
    "en": "Ciaran",
    "themeColor": "#C44065",
    "profile": {
      "shortIntro": "깔끔한 인간 부적술사로, 식물의 기운 속에서 회복하며 암기와 부적으로 판을 정리한다.",
      "quote": "정리는 끝났습니다. 남은 건 부적을 붙일 자리와 물러날 적뿐입니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "무협",
        "race": "인간",
        "job": "부적술사",
        "age": "22 세",
        "personality": "믿음직한, 깔끔한",
        "ability": "식물이 많은 곳에서 회복하는 능력",
        "weapon": "암기",
        "height": "168 cm",
        "weight": "49 kg",
        "measurements": "86 - 57 - 91"
      }
    },
    "folder": "136-ciaran",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "크셀라",
    "en": "Xella",
    "themeColor": "#74168C",
    "profile": {
      "shortIntro": "의심 많은 담피르 총잡이로, 능력을 약화시키는 힘과 레이저 권총으로 우위를 빼앗는다.",
      "quote": "자랑하던 능력, 방금 흐려졌죠? 이제 남은 건 진짜 실력뿐입니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "소프트SF",
        "race": "담피르",
        "job": "총잡이",
        "age": "221 세",
        "personality": "의심 많은, 나른한",
        "ability": "상대의 능력을 짧은 시간 동안 약화시키거나 무효화할 수 있는 능력",
        "weapon": "레이저 권총",
        "height": "169 cm",
        "weight": "55 kg",
        "measurements": "93 - 59 - 92"
      }
    },
    "folder": "137-xella",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "멜리아",
    "en": "Melia",
    "themeColor": "#EF5A26",
    "profile": {
      "shortIntro": "나태하지만 지적인 드라이어드 바드로, 기억을 건네는 법구와 노래로 전쟁을 기록한다.",
      "quote": "제가 뛰어다니긴 싫어요. 대신 이 기억을 받으면, 당신도 이미 전장을 본 겁니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "중세",
        "race": "드라이어드",
        "job": "바드",
        "age": "27 세",
        "personality": "지적인, 나태한",
        "ability": "기억을 다른 사람에게 전달할 수 있는 능력",
        "weapon": "법구",
        "height": "172 cm",
        "weight": "56 kg",
        "measurements": "88 - 60 - 91"
      }
    },
    "folder": "138-melia",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "모웬나",
    "en": "Morwenna",
    "themeColor": "#85F6A2",
    "profile": {
      "shortIntro": "성급한 마신족 검투사로, 특별한 이능 없이 도리깨와 육체의 압력으로 투기장을 누른다.",
      "quote": "심연의 힘 같은 건 기대하지 마. 널 쓰러뜨리는 건 그냥 내 도리깨야.",
      "basicInfo": {
        "gender": "여성",
        "world": "에레보스",
        "genre": "다크판타지",
        "race": "마신족",
        "job": "검투사",
        "age": "64 세",
        "personality": "성급한, 음침한",
        "ability": "알려지지 않음",
        "weapon": "도리깨",
        "height": "180 cm",
        "weight": "69 kg",
        "measurements": "106 - 61 - 98"
      }
    },
    "folder": "139-morwenna",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "에니드",
    "en": "Enid",
    "themeColor": "#FC228E",
    "profile": {
      "shortIntro": "포근한 염소 수인 방랑상인으로, 마법서와 장부로 죽은 자의 말을 잠시 빌린다.",
      "quote": "거래는 산 사람하고만 하는 게 아니랍니다. 다만 죽은 분들께는 더 정중해야 해요.",
      "basicInfo": {
        "gender": "여성",
        "world": "사프란해",
        "genre": "에코펑크",
        "race": "염소 수인",
        "job": "방랑상인",
        "age": "30 세",
        "personality": "꼼꼼한, 포근한",
        "ability": "죽은 자를 잠시 불러낼 수 있는 능력",
        "weapon": "마법서",
        "height": "170 cm",
        "weight": "58 kg",
        "measurements": "89 - 67 - 94"
      }
    },
    "folder": "140-enid",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  }
];
