// Character data only. Add/edit characters here, then refresh world.html.
// Base image paths are generated automatically from folder as:
// assets/characters/<folder>/main.webp, thumb.webp, doodle.webp, turn.webp
// Optional album slots are generated by the private Excel+ZIP importer from image file names.
// profile.basicInfo.world stores the character's 소속세계 from story-taxonomy.js.
// Set hidden: true to keep a template character out of the list.
window.CHARACTERS = [
  {
    "name": "레나",
    "en": "Lena",
    "themeColor": "#923834",
    "profile": {
      "shortIntro": "도망칠 길목에서 혼자 검을 뽑는 여우 귀의 기사.",
      "quote": "도망칠 사람은 도망쳐. 막는 건 내가 할 테니까.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "중세",
        "race": "여우 수인",
        "job": "기사",
        "age": "20 세",
        "personality": "정의감 넘친다",
        "ability": "알려지지 않음",
        "weapon": "검",
        "height": "168 cm",
        "weight": "55 kg",
        "measurements": "90 - 60 - 92"
      }
    },
    "folder": "001-lena",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "엘리아나",
    "en": "Eliana",
    "themeColor": "#96A7C4",
    "profile": {
      "shortIntro": "고양이처럼 웃으며 단서를 물고 사라지는 자유로운 탐정.",
      "quote": "문은 잠겼고, 발자국은 없고, 그러니까 재미있지.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "현대",
        "race": "인간",
        "job": "고양이탐정",
        "age": "30 ~ 39 세",
        "personality": "자유분방하다",
        "ability": "알려지지 않음",
        "weapon": "없음",
        "height": "168 cm",
        "weight": "50 kg",
        "measurements": "93 - 58 - 91"
      }
    },
    "folder": "002-eliana",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "스칼렛",
    "en": "Scarlett",
    "themeColor": "#9C2D34",
    "profile": {
      "shortIntro": "미소 하나로 방의 주도권을 가져가는 뱀파이어 귀족.",
      "quote": "초대받지 않은 손님도 예의만 알면 피는 덜 흘려.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "중세",
        "race": "뱀파이어",
        "job": "귀족",
        "age": "800 세\n(추정)",
        "personality": "고혹적이다",
        "ability": "알려지지 않음",
        "weapon": "없음",
        "height": "168 cm",
        "weight": "48 kg",
        "measurements": "94 - 56 - 93"
      }
    },
    "folder": "003-scarlett",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "루시엘",
    "en": "Luciel",
    "themeColor": "#6E479E",
    "profile": {
      "shortIntro": "무대 밖에서도 품위를 잃지 않는 우아한 배우.",
      "quote": "울어야 할 때 웃는 것, 그게 진짜 연기예요.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "현대",
        "race": "인간",
        "job": "배우",
        "age": "24 세",
        "personality": "우아하다",
        "ability": "알려지지 않음",
        "weapon": "없음",
        "height": "168 cm",
        "weight": "50 kg",
        "measurements": "92 - 56 - 91"
      }
    },
    "folder": "004-luciel",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "루나 페라노",
    "en": "Luna Ferrano",
    "themeColor": "#6F4A9E",
    "profile": {
      "shortIntro": "주먹과 렌치로 고장 난 세상을 두드리는 늑대 정비공.",
      "quote": "말로 안 풀리면 한 대 치고 다시 맞춰 보자.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "사이버펑크",
        "race": "늑대인간",
        "job": "정비공",
        "age": "30 세",
        "personality": "호전적이다",
        "ability": "알려지지 않음",
        "weapon": "없음(주먹)",
        "height": "168 cm",
        "weight": "58 kg",
        "measurements": "96 - 58 - 98"
      }
    },
    "folder": "005-lunaFerrano",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "엘라비야",
    "en": "Elabiah",
    "themeColor": "#B3A4BE",
    "profile": {
      "shortIntro": "상처와 옷자락을 같은 손길로 꿰매는 섬세한 시녀.",
      "quote": "찢어진 건 버리는 게 아니라, 가장 안 보이는 곳부터 고치는 거예요.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "중세",
        "race": "인간",
        "job": "시녀/디자이너",
        "age": "400 세",
        "personality": "섬세하다",
        "ability": "죽어도 되살아 나는 능력",
        "weapon": "없음",
        "height": "167 cm",
        "weight": "49 kg",
        "measurements": "93 - 56 - 91"
      }
    },
    "folder": "006-elabiah",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "루나",
    "en": "Luna",
    "themeColor": "#B7A2E0",
    "profile": {
      "shortIntro": "얌전한 얼굴로 모두가 놓친 절차를 기억하는 시녀.",
      "quote": "저는 조용했을 뿐이에요. 보지 않은 건 아니에요.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "중세",
        "race": "인간",
        "job": "시녀",
        "age": "27 세",
        "personality": "얌전하다",
        "ability": "알려지지 않음",
        "weapon": "없음",
        "height": "169 cm",
        "weight": "52 kg",
        "measurements": "92 - 56 - 91"
      }
    },
    "folder": "007-luna",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "레이나",
    "en": "Raina",
    "themeColor": "#6BAFF2",
    "profile": {
      "shortIntro": "호기심이 먼저 달려가고 수류탄이 뒤따르는 연구원.",
      "quote": "폭발 반응도 관찰값이에요. 조금 멀리서 보면요.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "미래",
        "race": "인간",
        "job": "연구원",
        "age": "21 세",
        "personality": "활발하고 호기심이 많다",
        "ability": "알려지지 않음",
        "weapon": "수류탄",
        "height": "165 cm",
        "weight": "48 kg",
        "measurements": "88 - 58 - 89"
      }
    },
    "folder": "008-raina",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "취화선",
    "en": "Chihwaseon",
    "themeColor": "#4A3A67",
    "profile": {
      "shortIntro": "술잔이 비워질수록 의리가 더 뜨거워지는 무술가.",
      "quote": "한잔 받았으면 한 번은 같이 맞아 줘야지.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "무협",
        "race": "인간",
        "job": "무술가",
        "age": "25 세",
        "personality": "자유분방하고 의리있다",
        "ability": "술을 마시면 강해지는 능력",
        "weapon": "없음(주먹)",
        "height": "168 cm",
        "weight": "53 kg",
        "measurements": "96 - 59 - 96"
      }
    },
    "folder": "009-chihwaseon",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "에리사 블랙문",
    "en": "Erissa Blackmoon",
    "themeColor": "#461766",
    "profile": {
      "shortIntro": "오만한 천재성이 폐허 위에 실험대를 차리는 다크엘프.",
      "quote": "윤리는 기록해 둬. 성공하면 나중에 읽어 줄게.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "좀비 아포칼립스",
        "race": "다크엘프",
        "job": "매드 사이언티스트",
        "age": "200 세",
        "personality": "오만하고 똑똑하다",
        "ability": "알려지지 않음",
        "weapon": "없음",
        "height": "172 cm",
        "weight": "62 kg",
        "measurements": "120 - 60 - 95"
      }
    },
    "folder": "010-erissaBlackmoon",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "시라예 에일마리스",
    "en": "Shiraye Ailmaris",
    "themeColor": "#E11729",
    "profile": {
      "shortIntro": "응석 섞인 목소리로 저격 명령을 내리는 엘프 보스.",
      "quote": "나 대신 화내 줘. 조준은 내가 할게.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "호러",
        "race": "엘프",
        "job": "마피아 보스",
        "age": "170 세",
        "personality": "응석쟁이",
        "ability": "알려지지 않음",
        "weapon": "저격총",
        "height": "168 cm",
        "weight": "55 kg",
        "measurements": "115 - 56 - 92"
      }
    },
    "folder": "011-shirayeAilmaris",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "반 팔레혼",
    "en": "Van Palaeon",
    "themeColor": "#0FA383",
    "profile": {
      "shortIntro": "소심하지만 들은 판결문은 평생 잊지 않는 코볼트 판사.",
      "quote": "기억하고 싶어서 기억하는 게 아닙니다. 그래서 더 공정해야 해요.",
      "basicInfo": {
        "gender": "여성",
        "world": "루미아",
        "genre": "일상",
        "race": "코볼트",
        "job": "판사",
        "age": "550 세 이상",
        "personality": "소심하다",
        "ability": "한번 보거나 들은 것을 잊지 않는 능력",
        "weapon": "없음",
        "height": "164 cm",
        "weight": "49 kg",
        "measurements": "78 - 56 - 85"
      }
    },
    "folder": "012-vanPalaeon",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "에스트릴 일라스",
    "en": "Estril Illas",
    "themeColor": "#5D46AE",
    "profile": {
      "shortIntro": "무거운 갑옷 속에 집착을 숨긴 다크엘프 중장보병.",
      "quote": "한 번 지키겠다고 정한 자리는, 내 무덤이 돼도 좋아.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "다크판타지",
        "race": "다크엘프",
        "job": "중장보병",
        "age": "81 세",
        "personality": "쿨하고 집착이 심하다",
        "ability": "타인으로 변신할 수 있는 능력",
        "weapon": "창,단검",
        "height": "171 cm",
        "weight": "60 kg",
        "measurements": "115 - 56 - 94"
      }
    },
    "folder": "013-estrilIllas",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "로위나",
    "en": "Rowina",
    "themeColor": "#1770D9",
    "profile": {
      "shortIntro": "물길과 전장을 똑같이 헤엄치는 자유로운 아수라 현자.",
      "quote": "숨이 막힌다고? 그럼 다른 방식으로 숨 쉬면 되지.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "헌터물",
        "race": "아수라",
        "job": "현자",
        "age": "22 세",
        "personality": "자유분방하다",
        "ability": "물에서 숨을 쉴 수 있는 능력",
        "weapon": "마법지팡이",
        "height": "168 cm",
        "weight": "55 kg",
        "measurements": "103 - 57 - 91"
      }
    },
    "folder": "014-rowina",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "민디",
    "en": "Mindy",
    "themeColor": "#76789D",
    "profile": {
      "shortIntro": "주먹보다 먼저 그림자를 실체로 세우는 냉혹한 유령 파이터.",
      "quote": "벽에 그린 주먹도 맞으면 아파.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "수사물",
        "race": "유령",
        "job": "파이터",
        "age": "85 세",
        "personality": "냉혹하다",
        "ability": "그림을 실체화 할 수 있는 능력",
        "weapon": "없음",
        "height": "170 cm",
        "weight": "측정불가",
        "measurements": "88 - 52 - 88"
      }
    },
    "folder": "015-mindy",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "세로단",
    "en": "Serothan",
    "themeColor": "#AD6ADF",
    "profile": {
      "shortIntro": "차가운 숨으로 춤의 온도를 바꾸는 관능적인 마신족 무희.",
      "quote": "가까이 오지 마. 내 숨결은 박수보다 차가우니까.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "하이 판타지",
        "race": "마신족",
        "job": "무희",
        "age": "62 세",
        "personality": "관능적이다",
        "ability": "차가운 입김을 불 수 있는 능력",
        "weapon": "없음",
        "height": "178 cm",
        "weight": "68 kg",
        "measurements": "123 - 58 - 108"
      }
    },
    "folder": "016-serothan",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "나기르",
    "en": "Nagir",
    "themeColor": "#9F76C7",
    "profile": {
      "shortIntro": "영원을 짊어진 채 작은 일에도 예민해지는 거인 요술사.",
      "quote": "오래 산다고 익숙해지는 건 아니야. 상처도, 별빛도.",
      "basicInfo": {
        "gender": "여성",
        "world": "아스트라",
        "genre": "SF",
        "race": "거인",
        "job": "요술사",
        "age": "39 세",
        "personality": "신경과민",
        "ability": "영원히 살 수 있는 능력",
        "weapon": "마법서",
        "height": "252 cm",
        "weight": "145 kg",
        "measurements": "138 - 76 - 128"
      }
    },
    "folder": "017-nagir",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "크리스틴 커튼",
    "en": "Kristen Cutton",
    "themeColor": "#AA834B",
    "profile": {
      "shortIntro": "화살보다 먼저 농담을 날리는 작은 하플링 궁수.",
      "quote": "무게를 줄이면 걱정도 날아가요. 가끔 사람도요.",
      "basicInfo": {
        "gender": "여성",
        "world": "루미아",
        "genre": "멜로",
        "race": "하플링",
        "job": "궁수",
        "age": "75 세",
        "personality": "재미있다",
        "ability": "사물의 무게를 조종할 수 있는 능력",
        "weapon": "활",
        "height": "112 cm",
        "weight": "27 kg",
        "measurements": "64 - 50 - 67"
      }
    },
    "folder": "018-kristenCutton",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "시라",
    "en": "Searra",
    "themeColor": "#CDD25E",
    "profile": {
      "shortIntro": "독기와 규율로 죄수들을 눌러 세우는 드레이크 교도관.",
      "quote": "규칙을 씹었으면, 이제 독도 삼켜 봐.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "뉴클리어 아포칼립스",
        "race": "드레이크",
        "job": "교도관",
        "age": "62 세",
        "personality": "강압적이다",
        "ability": "독을 다룰 수 있는 능력",
        "weapon": "쌍장창",
        "height": "172 cm",
        "weight": "63 kg",
        "measurements": "118 - 58 - 98"
      }
    },
    "folder": "019-searra",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "루시아 녹스",
    "en": "Lucia Nox",
    "themeColor": "#4E1187",
    "profile": {
      "shortIntro": "함성 하나로 경기장을 흔드는 마인 검투사.",
      "quote": "방패 뒤에 숨어도 소리는 못 막아.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "로우 판타지",
        "race": "마인",
        "job": "검투사",
        "age": "77 세",
        "personality": "용감하다",
        "ability": "큰 소리를 내서 음파를 방출하는 능력",
        "weapon": "검, 방패",
        "height": "178 cm",
        "weight": "70 kg",
        "measurements": "118 - 63 - 108"
      }
    },
    "folder": "020-luciaNox",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "bra",
      "cookmag"
    ]
  },
  {
    "name": "에시",
    "en": "Essy",
    "themeColor": "#FA3EA1",
    "profile": {
      "shortIntro": "순진한 얼굴로 여러 목숨의 무게를 안고 걷는 유령 사령술사.",
      "quote": "죽음이 끝이라면, 왜 아직 이렇게 말을 걸까요?",
      "basicInfo": {
        "gender": "여성",
        "world": "에레보스",
        "genre": "코즈믹 호러",
        "race": "유령",
        "job": "사령술사",
        "age": "46 세",
        "personality": "착하고 순진하다",
        "ability": "여러개의 목숨을 가지고 있는 능력",
        "weapon": "낫",
        "height": "172 cm",
        "weight": "측정불가",
        "measurements": "102 - 62 - 100"
      }
    },
    "folder": "021-essy",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "오투르쿠",
    "en": "Othurcu",
    "themeColor": "#F34BA2",
    "profile": {
      "shortIntro": "느긋한 기도로 죽은 자의 숨을 되돌리는 용인 사제.",
      "quote": "서두르지 마세요. 돌아오는 길도 길 수 있으니까요.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "바이오펑크",
        "race": "용인",
        "job": "사제",
        "age": "43 세",
        "personality": "여유롭다",
        "ability": "죽은 자를 되살릴 수 있는 능력",
        "weapon": "스태프",
        "height": "183 cm",
        "weight": "106 kg",
        "measurements": "112 - 68 - 108"
      }
    },
    "folder": "022-othurcu",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "나이브",
    "en": "Nive",
    "themeColor": "#09A2F8",
    "profile": {
      "shortIntro": "장난스러운 하프 선율로 내일의 균열을 엿보는 사티로스 바드.",
      "quote": "미래가 보였냐고? 응, 그래서 더 웃겨.",
      "basicInfo": {
        "gender": "여성",
        "world": "루미아",
        "genre": "학원물",
        "race": "사티로스",
        "job": "바드",
        "age": "21 세",
        "personality": "장난스럽다",
        "ability": "미래를 볼 수 있는 능력",
        "weapon": "하프",
        "height": "163 cm",
        "weight": "65 kg",
        "measurements": "96 - 66 - 98"
      }
    },
    "folder": "023-nive",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "아리엘",
    "en": "Ariel",
    "themeColor": "#A94532",
    "profile": {
      "shortIntro": "게으른 미소 아래 불꽃을 삼키는 긴 꼬리의 인어 인형술사.",
      "quote": "움직이기 귀찮으니까, 인형들이 대신 춤춰 줄 거야.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "포스트 아포칼립스",
        "race": "인어",
        "job": "인형술사",
        "age": "20 세",
        "personality": "게으르다",
        "ability": "불꽃을 먹으면 강해지는 능력",
        "weapon": "삼지창",
        "height": "상반신 약 88 cm,\n전체 체장 약 310 cm",
        "weight": "72 kg",
        "measurements": "82 - 57 - 88\n(꼬리기부둘레)"
      }
    },
    "folder": "024-ariel",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "가넷",
    "en": "Garnet",
    "themeColor": "#7C2B2A",
    "profile": {
      "shortIntro": "의리와 광기를 같은 칼집에 넣고 다니는 마수족 암살자.",
      "quote": "등 뒤를 맡긴 친구라면, 앞의 적은 내가 벨게.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "무협",
        "race": "마수족",
        "job": "암살자",
        "age": "33 세",
        "personality": "광기있고 카리스마 있음",
        "ability": "알려지지 않음",
        "weapon": "일본도",
        "height": "148 cm",
        "weight": "53 kg",
        "measurements": "98 - 55 - 93"
      }
    },
    "folder": "025-garnet",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "울린",
    "en": "Wulin",
    "themeColor": "#99A956",
    "profile": {
      "shortIntro": "충동 하나로 약병을 던지는 신수족 연금술사 빌런.",
      "quote": "결과는 몰라. 그래서 던지는 거야.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "다크히어로물",
        "race": "신수족",
        "job": "연금술사/빌런",
        "age": "58 세",
        "personality": "충동적이다",
        "ability": "알려지지 않음",
        "weapon": "플라스크 유리병",
        "height": "156 cm",
        "weight": "76 kg",
        "measurements": "94 - 57 - 94"
      }
    },
    "folder": "026-wulin",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "플로라 데이지베이",
    "en": "Flora Daisybay",
    "themeColor": "#A53581",
    "profile": {
      "shortIntro": "재채기 한 번으로 분위기까지 바뀌는 요정 바리스타.",
      "quote": "커피는 달게, 사고는 더 달콤하게!",
      "basicInfo": {
        "gender": "여성",
        "world": "루미아",
        "genre": "마법소녀물",
        "race": "요정",
        "job": "바리스타/마법소녀",
        "age": "2000 세",
        "personality": "낙천적이다",
        "ability": "재채기하면 인격이 바뀌는 능력",
        "weapon": "마법봉",
        "height": "102 cm",
        "weight": "18 kg",
        "measurements": "55 - 43 - 58"
      }
    },
    "folder": "027-floraDaisybay",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "미브나스",
    "en": "Mibnas",
    "themeColor": "#27D3DA",
    "profile": {
      "shortIntro": "절벽 같은 체구로 냉정하게 염주를 굴리는 거인 파계승.",
      "quote": "작은 목소리도 들린다. 그러니 거짓말은 크게 하지 마라.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "판타지",
        "race": "거인",
        "job": "파계승",
        "age": "4000 세",
        "personality": "냉정하다",
        "ability": "타인에게 빙의할 수 있는 능력",
        "weapon": "염주",
        "height": "12 ~ 15 m",
        "weight": "약 30 ~ 40 t",
        "measurements": "900 - 540 - 880"
      }
    },
    "folder": "028-mibnas",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "앨리스",
    "en": "Alice",
    "themeColor": "#7094CF",
    "profile": {
      "shortIntro": "밝은 귀를 쫑긋 세우고 사건 냄새를 쫓는 토끼 리포터.",
      "quote": "특종은 뛰어가는 사람보다 기다린 사람이 잡을 때도 있어요.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "현대 드라마",
        "race": "토끼 수인",
        "job": "리포터",
        "age": "23 세",
        "personality": "밝고 긍정적이다",
        "ability": "알려지지 않음",
        "weapon": "없음",
        "height": "150 cm",
        "weight": "40 kg",
        "measurements": "74 - 52 - 79"
      }
    },
    "folder": "029-alice",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "클로에",
    "en": "Chloe",
    "themeColor": "#7E6595",
    "profile": {
      "shortIntro": "귀여운 미소 뒤에 맞을수록 단단해지는 인형 메이드.",
      "quote": "더 때려도 돼요. 청소할 힘이 늘어나거든요.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "좀비 아포칼립스",
        "race": "구체관절인형",
        "job": "메이드",
        "age": "없음",
        "personality": "귀엽다",
        "ability": "싸울수록 강해지는 능력",
        "weapon": "건틀릿",
        "height": "162 cm",
        "weight": "39 kg",
        "measurements": "82 - 55 - 86"
      }
    },
    "folder": "030-chloe",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "키젤",
    "en": "Qeisel",
    "themeColor": "#3C7059",
    "profile": {
      "shortIntro": "피와 폭탄의 배치를 예술처럼 맞추는 아라크네 연금술사.",
      "quote": "흩뿌린 피도 설계하면 꽃처럼 터져.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "하이 판타지",
        "race": "아라크네",
        "job": "연금술사/빌런",
        "age": "25 세",
        "personality": "감성이 풍부하고 빈틈이 없다",
        "ability": "피를 원하는 형태로 바꿀 수 있는 능력",
        "weapon": "폭탄",
        "height": "체고 약 190c m,\n전체 전장 약 330 cm",
        "weight": "260 kg",
        "measurements": "106 - 58 - 96\n(접합부 기준)"
      }
    },
    "folder": "031-qeisel",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "라니스",
    "en": "Rhanis",
    "themeColor": "#CCAF78",
    "profile": {
      "shortIntro": "작은 손에 더블배럴샷건을 꼭 쥔 소심한 노움 소환사.",
      "quote": "무서우니까 부르는 거예요. 혼자 싸우긴 싫거든요.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "이세계",
        "race": "노움",
        "job": "소환사",
        "age": "25 세",
        "personality": "소심하다",
        "ability": "알려지지 않음",
        "weapon": "더블배럴샷건",
        "height": "100 cm",
        "weight": "19 kg",
        "measurements": "58 - 47 - 60"
      }
    },
    "folder": "032-rhanis",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "미사",
    "en": "Misa",
    "themeColor": "#AA91B3",
    "profile": {
      "shortIntro": "긴 꼬리를 말고도 낚싯대를 놓지 못하는 겁 많은 나가 어부.",
      "quote": "커다란 물고기보다 조용한 물결이 더 무서워요.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "호러",
        "race": "나가",
        "job": "어부",
        "age": "166 세",
        "personality": "겁이 많다",
        "ability": "알려지지 않음",
        "weapon": "낚시대",
        "height": "상반신 약 90 cm,\n전체 체장 약 480 cm",
        "weight": "170 kg",
        "measurements": "82 - 60 - 95\n(꼬리기부둘레)"
      }
    },
    "folder": "033-misa",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "아야",
    "en": "Aya",
    "themeColor": "#046B2D",
    "profile": {
      "shortIntro": "말보다 바람이 먼저 앞질러 가는 염소 수인 바람술사.",
      "quote": "내가 설명하는 동안에도, 총알은 이미 돌아갔어!",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "포스트 아포칼립스",
        "race": "염소 수인",
        "job": "바람술사",
        "age": "28 세",
        "personality": "말이 많다",
        "ability": "빠르게 움직일수 있는 능력",
        "weapon": "리볼버",
        "height": "170 cm",
        "weight": "67 kg",
        "measurements": "113 - 62 - 104"
      }
    },
    "folder": "034-aya",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "타닐라 엘라민",
    "en": "Tanila Ellamin",
    "themeColor": "#A17F1E",
    "profile": {
      "shortIntro": "식물의 속삭임을 듣고 포문을 여는 사심 없는 우드엘프 해적.",
      "quote": "풀잎이 가지 말라면 안 가. 대신 대포는 쏠 수 있지.",
      "basicInfo": {
        "gender": "여성",
        "world": "아스트라",
        "genre": "SF",
        "race": "우드엘프",
        "job": "우주해적",
        "age": "58 세",
        "personality": "사심이 없다",
        "ability": "식물의 말을 들을 수 있는 능력",
        "weapon": "곡사포",
        "height": "177 cm",
        "weight": "60 kg",
        "measurements": "108 - 58 - 93"
      }
    },
    "folder": "035-tanilaEllamin",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "셀리나",
    "en": "Celina",
    "themeColor": "#21F6CB",
    "profile": {
      "shortIntro": "타인의 재능을 알아보는 어른스러운 봉제인형 상인.",
      "quote": "값을 매기는 건 물건뿐이에요. 사람은 더 조심해야죠.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "로우 판타지",
        "race": "봉제인형",
        "job": "방랑상인",
        "age": "없음",
        "personality": "어른스럽다",
        "ability": "타인의 능력을 알 수 있는 능력",
        "weapon": "도리깨",
        "height": "166 cm",
        "weight": "8 kg",
        "measurements": "96 - 56 - 91"
      }
    },
    "folder": "036-celina",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "sakura",
      "bra"
    ]
  },
  {
    "name": "피프 가브리엘",
    "en": "Piff Gabriel",
    "themeColor": "#8E3C92",
    "profile": {
      "shortIntro": "실수처럼 날아와 불꽃을 삼키는 작은 임프 총독.",
      "quote": "앗, 그건 사고였어. 그런데 결과는 마음에 드네.",
      "basicInfo": {
        "gender": "여성",
        "world": "사프란해",
        "genre": "해적물",
        "race": "임프",
        "job": "총독",
        "age": "94 세",
        "personality": "부주의하다",
        "ability": "불꽃을 먹으면 강해지는 능력",
        "weapon": "수리검",
        "height": "95 cm",
        "weight": "18 kg",
        "measurements": "55 - 42 - 57"
      }
    },
    "folder": "037-piffGabriel",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "프레이야",
    "en": "Freya",
    "themeColor": "#B1A7E2",
    "profile": {
      "shortIntro": "햇빛 아래 더 완고해지는 하피 언데드사냥꾼.",
      "quote": "그늘로 숨어. 난 해가 뜰수록 더 못 물러나.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "영지물",
        "race": "하피",
        "job": "언데드사냥꾼",
        "age": "87 세",
        "personality": "고집불통이다",
        "ability": "햇빛에 노출되면 강해지는 능력",
        "weapon": "돌격소총",
        "height": "175 cm",
        "weight": "62 kg",
        "measurements": "95 - 54 - 96"
      }
    },
    "folder": "038-freya",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "록시",
    "en": "Roxy",
    "themeColor": "#35E323",
    "profile": {
      "shortIntro": "달빛이 비칠수록 신중한 주먹이 무거워지는 건달.",
      "quote": "성급하게 치면 손만 아파. 밤이 깊을 때까지 기다려.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "느와르",
        "race": "인간",
        "job": "건달",
        "age": "32 세",
        "personality": "신중하다",
        "ability": "달빛에 노출되면 강해지는 능력",
        "weapon": "너클",
        "height": "175 cm",
        "weight": "66 kg",
        "measurements": "105 - 60 - 98"
      }
    },
    "folder": "039-roxy",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "베가",
    "en": "Vega",
    "themeColor": "#56D1B9",
    "profile": {
      "shortIntro": "죽어도 과거로 돌아가 책임을 미루는 셰이프시프터 샤먼.",
      "quote": "실패했네. 좋아, 이번엔 다른 얼굴로 해 보자.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "어반 판타지",
        "race": "셰이프시프터",
        "job": "샤먼",
        "age": "28 세",
        "personality": "무책임하다",
        "ability": "죽으면 특정 과거로 이동하는 능력",
        "weapon": "철퇴",
        "height": "172 cm",
        "weight": "60 kg",
        "measurements": "92 - 62 - 94"
      }
    },
    "folder": "040-vega",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "box",
      "beach",
      "sakura"
    ]
  },
  {
    "name": "서아",
    "en": "Seoah",
    "themeColor": "#ED1C19",
    "profile": {
      "shortIntro": "헌신적인 손길로 공간까지 접어 약장을 여는 인형 약사.",
      "quote": "아픈 건 숨기지 마세요. 숨긴 곳도 제가 열어 볼게요.",
      "basicInfo": {
        "gender": "여성",
        "world": "루미아",
        "genre": "일상",
        "race": "구체관절인형",
        "job": "약사",
        "age": "없음",
        "personality": "헌신적인",
        "ability": "공간을 절단해 물건들을 보관할 수 있는 능력",
        "weapon": "자동권총",
        "height": "169 cm",
        "weight": "49 kg",
        "measurements": "80 - 54 - 84"
      }
    },
    "folder": "041-seoah",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "valen"
    ]
  },
  {
    "name": "리브라",
    "en": "Libra",
    "themeColor": "#A9708A",
    "profile": {
      "shortIntro": "책장을 넘기듯 세상의 균형을 맞추는 부지런한 담피르 사서.",
      "quote": "조용히 해. 책도 화나면 도끼보다 무거워.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "궁정물",
        "race": "담피르",
        "job": "사서",
        "age": "32 세",
        "personality": "부지런하다",
        "ability": "책을 자유자재로 조작할 수 있는 능력",
        "weapon": "대도끼",
        "height": "171 cm",
        "weight": "58 kg",
        "measurements": "96 - 58 - 93"
      }
    },
    "folder": "042-libra",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "sakura"
    ]
  },
  {
    "name": "우분",
    "en": "Wubun",
    "themeColor": "#D88A2E",
    "profile": {
      "shortIntro": "큰 뿔 아래 사교적인 웃음을 숨긴 미노타우로스 결계사.",
      "quote": "들어오려면 이름부터 말해. 결계도 예의는 따지거든.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "무협",
        "race": "미노타우로스",
        "job": "결계사",
        "age": "35 세",
        "personality": "사교적이다",
        "ability": "알려지지 않음",
        "weapon": "할버드",
        "height": "260 cm",
        "weight": "340 kg",
        "measurements": "178 - 112 - 181"
      }
    },
    "folder": "043-wubun",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "beach"
    ]
  },
  {
    "name": "세레나",
    "en": "Serena",
    "themeColor": "#4A9E87",
    "profile": {
      "shortIntro": "상냥한 춤사위 뒤에 월아삽을 숨긴 백조 수인 무희.",
      "quote": "춤은 부드럽게, 베는 건 망설임 없이.",
      "basicInfo": {
        "gender": "여성",
        "world": "사프란해",
        "genre": "항해물",
        "race": "백조수인",
        "job": "무희",
        "age": "25 세",
        "personality": "상냥하다",
        "ability": "알려지지 않음",
        "weapon": "월아삽",
        "height": "169 cm",
        "weight": "52 kg",
        "measurements": "92 - 58 - 90"
      }
    },
    "folder": "044-serena",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "sakura"
    ]
  },
  {
    "name": "타키온",
    "en": "Tachyon",
    "themeColor": "#2B78D3",
    "profile": {
      "shortIntro": "자신감 하나로 용의 등까지 올라탄 다크엘프 라이더.",
      "quote": "높은 데가 무섭다고? 그럼 더 높이 올라가면 돼.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "히어로물",
        "race": "다크엘프",
        "job": "드래곤라이더",
        "age": "38 세",
        "personality": "자신감 있다",
        "ability": "알려지지 않음",
        "weapon": "갈고리창",
        "height": "178 cm",
        "weight": "63 kg",
        "measurements": "88 - 60 - 90"
      }
    },
    "folder": "045-tachyon",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "글루미",
    "en": "Gloomy",
    "themeColor": "#9C85BA",
    "profile": {
      "shortIntro": "우울한 렌즈로 아무도 보지 않는 진실을 찍는 캇파 사진작가.",
      "quote": "웃지 않아도 돼. 진짜 표정은 그다음 컷에 나오니까.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "범죄물",
        "race": "캇파",
        "job": "사진작가",
        "age": "785 세",
        "personality": "우울한",
        "ability": "알려지지 않음",
        "weapon": "독반지",
        "height": "167 cm",
        "weight": "53 kg",
        "measurements": "83 - 58 - 87"
      }
    },
    "folder": "046-gloomy",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "beach"
    ]
  },
  {
    "name": "러스트",
    "en": "Rust",
    "themeColor": "#ADBDA9",
    "profile": {
      "shortIntro": "고요한 손끝으로 용암과 기계를 다루는 골렘 메카닉.",
      "quote": "뜨겁다고 피하지 마. 식으면 움직이지 않거든.",
      "basicInfo": {
        "gender": "여성",
        "world": "아스트라",
        "genre": "스페이스 웨스턴",
        "race": "골렘",
        "job": "메카닉",
        "age": "62 세",
        "personality": "고요한",
        "ability": "용암을 다룰 수 있는 능력",
        "weapon": "병",
        "height": "168 cm",
        "weight": "70 kg",
        "measurements": "86 - 61 - 90"
      }
    },
    "folder": "047-rust",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "니리",
    "en": "Niri",
    "themeColor": "#906B41",
    "profile": {
      "shortIntro": "영적인 날개 아래 괴물의 몸을 숨긴 나비 메이드.",
      "quote": "차를 따를까요, 아니면 이 몸을 먼저 접어 드릴까요?",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "감염병 아포칼립스",
        "race": "나비",
        "job": "메이드",
        "age": "32 세",
        "personality": "영적인",
        "ability": "신체를 괴물화 할 수 있는 능력",
        "weapon": "탄토",
        "height": "203 cm",
        "weight": "82 kg",
        "measurements": "112 - 61 - 105"
      }
    },
    "folder": "048-niri",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "maid"
    ]
  },
  {
    "name": "시시",
    "en": "Xi-Xi",
    "themeColor": "#355CF1",
    "profile": {
      "shortIntro": "소심하게 말하고 그림자 속으로 사라지는 강시 로봇공학자.",
      "quote": "괜찮아요, 저는 뒤에 있을게요. 아주 뒤, 그림자 안쪽에.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "호러",
        "race": "강시",
        "job": "로봇공학자",
        "age": "25 세",
        "personality": "소심한",
        "ability": "그림자를 통해 이동할 수 있는 능력",
        "weapon": "핸드캐넌",
        "height": "169 cm",
        "weight": "54 kg",
        "measurements": "86 - 57 - 88"
      }
    },
    "folder": "049-xi-xi",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "니나",
    "en": "Nina",
    "themeColor": "#2BCBC3",
    "profile": {
      "shortIntro": "사려 깊은 기도로 꿈을 고치는 봉제인형 수도사.",
      "quote": "악몽도 누군가에게는 구조 신호일 수 있어요.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "디젤펑크",
        "race": "봉제인형",
        "job": "수도사",
        "age": "없음",
        "personality": "사려 깊은",
        "ability": "꿈을 조작할 수 있는 능력",
        "weapon": "마체테",
        "height": "152 cm",
        "weight": "26 kg",
        "measurements": "78 - 56 - 82"
      }
    },
    "folder": "050-nina",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "초아",
    "en": "Choa",
    "themeColor": "#45DC24",
    "profile": {
      "shortIntro": "자유로운 예언으로 남의 기억까지 흐리게 하는 미라.",
      "quote": "잊어도 돼. 대신 내가 본 건 절대 사라지지 않아.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "무협",
        "race": "미라",
        "job": "예언자",
        "age": "29 세",
        "personality": "자유분방한",
        "ability": "망각을 유발할 수 있는 능력",
        "weapon": "차크람",
        "height": "166 cm",
        "weight": "49 kg",
        "measurements": "84 - 58 - 86"
      }
    },
    "folder": "051-choa",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "로건",
    "en": "Logan",
    "themeColor": "#8B7D11",
    "profile": {
      "shortIntro": "낡은 화승총보다 굳센 등을 먼저 내미는 늑대 경찰관.",
      "quote": "법이 늦게 와도, 나는 먼저 서 있을 수 있어.",
      "basicInfo": {
        "gender": "여성",
        "world": "루미아",
        "genre": "일상",
        "race": "늑대수인",
        "job": "경찰관",
        "age": "25 세",
        "personality": "강인한",
        "ability": "알려지지 않음",
        "weapon": "화승총",
        "height": "168 cm",
        "weight": "57 kg",
        "measurements": "92 - 58 - 94"
      }
    },
    "folder": "052-logan",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "조이",
    "en": "Joy",
    "themeColor": "#98EF12",
    "profile": {
      "shortIntro": "다정한 뿌리로 폭풍 속에서도 공을 놓지 않는 엔트 선수.",
      "quote": "넘어지면 잡아 줄게. 대신 다시 뛰어야 해.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "포스트 아포칼립스",
        "race": "엔트",
        "job": "운동선수",
        "age": "68 세",
        "personality": "다정한",
        "ability": "자신 주변에 작은 폭풍을 만들 수 있는 능력",
        "weapon": "검",
        "height": "168 cm",
        "weight": "52 kg",
        "measurements": "80 - 57 - 83"
      }
    },
    "folder": "053-joy",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "미아",
    "en": "Mia",
    "themeColor": "#15D927",
    "profile": {
      "shortIntro": "수줍게 미소 짓고 불운을 슬쩍 건네는 슬라임 사신.",
      "quote": "미안해요. 제 인사는 가끔 불길하게 묻어요.",
      "basicInfo": {
        "gender": "여성",
        "world": "사프란해",
        "genre": "실크로드판타지",
        "race": "슬라임",
        "job": "사신",
        "age": "26 세",
        "personality": "수줍은",
        "ability": "상대에게 불운을 부여할 수 있는 능력",
        "weapon": "낫",
        "height": "98 cm",
        "weight": "10 kg",
        "measurements": "51 - 42 -54"
      }
    },
    "folder": "054-mia",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "가은",
    "en": "GaEun",
    "themeColor": "#1F8857",
    "profile": {
      "shortIntro": "착한 목소리로 인형을 세워 수업을 이어가는 리치 교사.",
      "quote": "죽었다고 배움까지 멈추면 선생님이 섭섭하죠.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "동양판타지",
        "race": "리치",
        "job": "교사",
        "age": "외형 39세 / 실제 180세",
        "personality": "착한",
        "ability": "인형을 움직일 수 있는 능력",
        "weapon": "와키자시",
        "height": "202 cm",
        "weight": "72 kg",
        "measurements": "98 - 67 - 100"
      }
    },
    "folder": "055-gaeun",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "실비아",
    "en": "Sylvia",
    "themeColor": "#2A4C4F",
    "profile": {
      "shortIntro": "예민한 미각과 독의 손끝을 함께 지닌 문엘프 요리사.",
      "quote": "한 입이면 충분해. 맛도, 독도.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "영지물",
        "race": "문엘프",
        "job": "요리사",
        "age": "97 세",
        "personality": "예민한",
        "ability": "상대에게 닿으면 독을 주입하는 능력",
        "weapon": "식칼",
        "height": "166 cm",
        "weight": "48 kg",
        "measurements": "84 - 55 - 86"
      }
    },
    "folder": "056-sylvia",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "비비안",
    "en": "Vivian",
    "themeColor": "#637115",
    "profile": {
      "shortIntro": "차가운 눈으로 폭풍의 결을 읽는 천인 탐정.",
      "quote": "바람은 거짓말을 못 해. 흔적만 빙빙 돌릴 뿐이지.",
      "basicInfo": {
        "gender": "여성",
        "world": "사프란해",
        "genre": "실크로드판타지",
        "race": "천인",
        "job": "탐정",
        "age": "34 세",
        "personality": "차가운",
        "ability": "자신 주변에 작은 폭풍을 만들 수 있는 능력",
        "weapon": "쌍도끼",
        "height": "178 cm",
        "weight": "65 kg",
        "measurements": "95 - 60 - 97"
      }
    },
    "folder": "057-vivian",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "디아나",
    "en": "Diana",
    "themeColor": "#A1DF56",
    "profile": {
      "shortIntro": "꽃향기와 독을 같은 몸에 품은 계획적인 나가 플로리스트.",
      "quote": "꽃은 예쁘게 피고, 독은 조용히 번져요.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "첩보",
        "race": "나가",
        "job": "플로리스트",
        "age": "35 세",
        "personality": "계획적인",
        "ability": "몸속의 독을 힘으로 바꿀 수 있는 능력",
        "weapon": "타로 카드",
        "height": "상반신 약 108cm,\n전체 체장 약 690 cm",
        "weight": "235 kg",
        "measurements": "101 - 63 -  96\n(꼬리기부둘레)"
      }
    },
    "folder": "058-diana",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "리제",
    "en": "Lize",
    "themeColor": "#DDD529",
    "profile": {
      "shortIntro": "침착한 미소로 빛을 꺾어 표적 뒤에 서는 구울 사냥꾼.",
      "quote": "날 못 봤다면, 이미 반은 잡힌 거야.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "게임판타지",
        "race": "구울",
        "job": "현상금사냥꾼",
        "age": "34 세",
        "personality": "침착한",
        "ability": "빛을 굴절시켜 모습을 감출 수 있는 능력",
        "weapon": "갈고리",
        "height": "180 cm",
        "weight": "58 kg",
        "measurements": "88 - 58 - 92"
      }
    },
    "folder": "059-lize",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "그레이스",
    "en": "Grace",
    "themeColor": "#7A6670",
    "profile": {
      "shortIntro": "연기처럼 흩어졌다가 자신감 있게 돌아오는 인간 사제.",
      "quote": "믿음은 붙잡는 게 아니야. 흩어져도 다시 모이는 거지.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "선협",
        "race": "인간",
        "job": "사제",
        "age": "29 세",
        "personality": "자신감 있는",
        "ability": "몸을 연기처럼 흩어지게 할 수 있는 능력",
        "weapon": "스태프",
        "height": "181 cm",
        "weight": "63 kg",
        "measurements": "92 - 61 - 94"
      }
    },
    "folder": "060-grace",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "엘레나",
    "en": "Elena",
    "themeColor": "#0F6E6E",
    "profile": {
      "shortIntro": "잔을 닦듯 상황을 정리하는 꼼꼼한 안드로이드 바텐더.",
      "quote": "주문은 정확히. 실수는 손님보다 제가 더 싫어합니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "바이오펑크",
        "race": "안드로이드",
        "job": "바텐더",
        "age": "450 세",
        "personality": "꼼꼼한",
        "ability": "알려지지 않음",
        "weapon": "레이피어",
        "height": "176 cm",
        "weight": "68 kg",
        "measurements": "94 - 59 -94"
      }
    },
    "folder": "061-elena",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "이네스",
    "en": "Ines",
    "themeColor": "#939FDC",
    "profile": {
      "shortIntro": "당찬 눈빛으로 독과 단서를 함께 추적하는 유령 탐정.",
      "quote": "죽은 뒤에도 사건은 끝까지 따라붙더라.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "궁정물",
        "race": "유령",
        "job": "탐정",
        "age": "33 세",
        "personality": "당찬",
        "ability": "독을 다룰 수 있는 능력",
        "weapon": "노다치",
        "height": "175 cm",
        "weight": "57 kg",
        "measurements": "96 - 58 -96"
      }
    },
    "folder": "062-ines",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "비앙카",
    "en": "Bianca",
    "themeColor": "#5A32FF",
    "profile": {
      "shortIntro": "불안한 왕관 아래 괴력을 감춘 인간 왕족.",
      "quote": "떨리는 손이라도, 잡아야 할 건 놓치지 않을래.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "설원판타지",
        "race": "인간",
        "job": "왕족",
        "age": "32 세",
        "personality": "불안한",
        "ability": "괴력을 발휘할 수 있는 능력",
        "weapon": "워픽",
        "height": "168 cm",
        "weight": "56 kg",
        "measurements": "91 - 56 - 90"
      }
    },
    "folder": "063-bianca",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "japanFestival"
    ]
  },
  {
    "name": "티나",
    "en": "Tina",
    "themeColor": "#783D52",
    "profile": {
      "shortIntro": "명랑한 날갯짓으로 공격의 힘을 빼앗는 요정 스캐빈저.",
      "quote": "그거 버릴 거면 제가 쓸게요. 공격도 재활용되거든요!",
      "basicInfo": {
        "gender": "여성",
        "world": "사프란해",
        "genre": "실크로드판타지",
        "race": "요정",
        "job": "스캐빈저",
        "age": "29 세",
        "personality": "명랑한",
        "ability": "상대의 공격 에너지를 흡수할 수 있는 능력",
        "weapon": "쌍단검",
        "height": "148 cm",
        "weight": "39 kg",
        "measurements": "76 - 54 - 79"
      }
    },
    "folder": "064-tina",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "아이리스",
    "en": "Iris",
    "themeColor": "#06D291",
    "profile": {
      "shortIntro": "까칠한 말투와 비녀 하나로 선을 긋는 쥐 수인 도사.",
      "quote": "가까이 오지 마. 부적보다 내 성질이 먼저 나가.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "동양판타지",
        "race": "쥐 수인",
        "job": "도사",
        "age": "233 세",
        "personality": "까칠한",
        "ability": "알려지지 않음",
        "weapon": "비녀",
        "height": "168 cm",
        "weight": "53 kg",
        "measurements": "96 - 56 - 89"
      }
    },
    "folder": "065-iris",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "에이미",
    "en": "Amy",
    "themeColor": "#B0BC19",
    "profile": {
      "shortIntro": "불안한 발소리로도 자리를 지키는 유령 경비병.",
      "quote": "무서워도 순찰은 돌아요. 누군가는 문을 봐야 하니까.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "유령수사물",
        "race": "유령",
        "job": "경비병",
        "age": "21 세",
        "personality": "불안한",
        "ability": "알려지지 않음",
        "weapon": "없음",
        "height": "158 cm",
        "weight": "43 kg",
        "measurements": "78 - 56 - 82"
      }
    },
    "folder": "066-amy",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "연화",
    "en": "LianHua",
    "themeColor": "#3C5FDE",
    "profile": {
      "shortIntro": "착한 마음으로 염주를 굴리는 마신족 낭인.",
      "quote": "베지 않아도 끝나는 싸움이면, 그쪽을 고르고 싶어.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "신협",
        "race": "마신족",
        "job": "낭인",
        "age": "20 세",
        "personality": "착한",
        "ability": "알려지지 않음",
        "weapon": "염주",
        "height": "168 cm",
        "weight": "52 kg",
        "measurements": "98 - 58 -92"
      }
    },
    "folder": "067-lianHua",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "가온",
    "en": "Gaon",
    "themeColor": "#D01DB7",
    "profile": {
      "shortIntro": "대담한 눈으로 사냥감의 힘부터 꺾는 양 수인 사냥꾼.",
      "quote": "강한 척해도 돼. 네 힘은 곧 조용해질 테니까.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "감염병 아포칼립스",
        "race": "양 수인",
        "job": "사냥꾼",
        "age": "31 세",
        "personality": "대담한",
        "ability": "상대의 능력을 짧은 시간 동안 약화시키거나 무효화할 수 있는 능력",
        "weapon": "곡월도",
        "height": "173 cm",
        "weight": "62 kg",
        "measurements": "105 - 60 - 94"
      }
    },
    "folder": "068-gaon",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "테이라",
    "en": "Theira",
    "themeColor": "#11F0AA",
    "profile": {
      "shortIntro": "수수께끼 같은 기도로 거대한 몸을 괴물처럼 일으키는 타이탄.",
      "quote": "고통은 벗는 것이 아니라, 더 큰 몸으로 견디는 것이다.",
      "basicInfo": {
        "gender": "여성",
        "world": "에레보스",
        "genre": "신화판타지",
        "race": "타이탄",
        "job": "고행사제",
        "age": "2500 세",
        "personality": "수수께끼 같은",
        "ability": "신체를 괴물화 할 수 있는 능력",
        "weapon": "홀리 심볼",
        "height": "13.5 m",
        "weight": "약 42 t",
        "measurements": "880 - 520 - 910"
      }
    },
    "folder": "069-theira",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "셀비",
    "en": "Selby",
    "themeColor": "#5EE466",
    "profile": {
      "shortIntro": "고집 센 네 팔로 대형망치를 들어 올리는 아수라 보스.",
      "quote": "내 말이 안 들리면 괜찮아. 곧 아무 소리도 못 들을 테니.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "판타지",
        "race": "아수라",
        "job": "마피아 보스",
        "age": "36 세",
        "personality": "고집 센",
        "ability": "상대의 청각을 일시적으로 마비시키는 능력",
        "weapon": "대형망치",
        "height": "174 cm",
        "weight": "62 kg",
        "measurements": "101 - 62 - 96"
      }
    },
    "folder": "070-selby",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "가일",
    "en": "Guile",
    "themeColor": "#E0DD49",
    "profile": {
      "shortIntro": "대담한 웃음으로 쿠크리를 빼 드는 곰 수인 총잡이.",
      "quote": "총알이 떨어져도 손은 남아 있지.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "나노펑크",
        "race": "곰 수인",
        "job": "총잡이",
        "age": "28 세",
        "personality": "대담한",
        "ability": "알려지지 않음",
        "weapon": "쿠크리",
        "height": "178 cm",
        "weight": "81 kg",
        "measurements": "108 - 72 - 104"
      }
    },
    "folder": "071-guile",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "스카",
    "en": "Scar",
    "themeColor": "#C0C288",
    "profile": {
      "shortIntro": "반항적인 눈빛으로 식칼을 닦는 늑대인간 집사.",
      "quote": "명령은 듣습니다. 마음까지 복종하진 않지만요.",
      "basicInfo": {
        "gender": "여성",
        "world": "루미아",
        "genre": "요리물",
        "race": "늑대인간",
        "job": "집사",
        "age": "34 세",
        "personality": "반항적인",
        "ability": "알려지지 않음",
        "weapon": "식칼",
        "height": "175 cm",
        "weight": "64 kg",
        "measurements": "96 - 61 - 98"
      }
    },
    "folder": "072-scar",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "라비",
    "en": "Rabi",
    "themeColor": "#BC4874",
    "profile": {
      "shortIntro": "논리적인 말투로 작은 생물의 틈까지 파고드는 토끼 첩자.",
      "quote": "문이 크면 의심받죠. 그래서 작아지는 겁니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "사이버펑크",
        "race": "토끼 수인",
        "job": "첩자",
        "age": "28 세",
        "personality": "논리적인",
        "ability": "작은 생물로 변신할 수 있는 능력",
        "weapon": "메이스",
        "height": "169 cm",
        "weight": "52 kg",
        "measurements": "82 - 57 - 86"
      }
    },
    "folder": "073-rabi",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "로나",
    "en": "Rona",
    "themeColor": "#00801E",
    "profile": {
      "shortIntro": "차분한 메스로 상처를 과거로 되돌리는 하프엘프 외과의.",
      "quote": "아프기 전으로 돌려 드릴게요. 대신 거짓말은 남습니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "에코펑크",
        "race": "하프엘프",
        "job": "외과의",
        "age": "36 세",
        "personality": "논리적인",
        "ability": "상처를 입기 전 상태로 몸을 되돌릴 수 있는 능력",
        "weapon": "독반지",
        "height": "172 cm",
        "weight": "58 kg",
        "measurements": "94 - 60 - 93"
      }
    },
    "folder": "074-rona",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "아니카",
    "en": "Anika",
    "themeColor": "#94DC09",
    "profile": {
      "shortIntro": "비밀스러운 웃음으로 폐허의 뒷길을 파는 구울 밀수꾼.",
      "quote": "모르는 게 안전한 물건도 있어. 사겠다면 더 비싸고.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "감염병 아포칼립스",
        "race": "구울",
        "job": "밀수꾼",
        "age": "32 세",
        "personality": "비밀스러운",
        "ability": "알려지지 않음",
        "weapon": "수리검",
        "height": "173 cm",
        "weight": "54 kg",
        "measurements": "88 - 56 - 89"
      }
    },
    "folder": "075-anika",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "가르카",
    "en": "Garka",
    "themeColor": "#75185C",
    "profile": {
      "shortIntro": "이성적인 손끝으로 트롤의 체구에 딱 맞는 옷을 재단하는 장인.",
      "quote": "천은 거짓말을 못 해. 몸의 진실을 따라 잘릴 뿐이지.",
      "basicInfo": {
        "gender": "여성",
        "world": "아스트라",
        "genre": "스페이스 오페라",
        "race": "트롤",
        "job": "재단사",
        "age": "524 세",
        "personality": "이성적인",
        "ability": "알려지지 않음",
        "weapon": "쌍검",
        "height": "208 cm",
        "weight": "116 kg",
        "measurements": "126 - 86 - 124"
      }
    },
    "folder": "076-garka",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "젤라",
    "en": "Zella",
    "themeColor": "#5C8479",
    "profile": {
      "shortIntro": "오만한 주문검으로 햇빛을 힘으로 삼는 와이트 배틀메이지.",
      "quote": "해가 뜨면 끝이라고? 아니, 그때부터 내 차례야.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "게임판타지",
        "race": "와이트",
        "job": "배틀메이지",
        "age": "25 세",
        "personality": "오만한",
        "ability": "햇빛에 노출되면 강해지는 능력",
        "weapon": "주술검",
        "height": "174 cm",
        "weight": "60 kg",
        "measurements": "94 - 58 - 91"
      }
    },
    "folder": "077-zella",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "나이아",
    "en": "Naia",
    "themeColor": "#65A7B4",
    "profile": {
      "shortIntro": "예민한 망치질로 햇빛까지 벼려 내는 루살카 대장장이.",
      "quote": "불평할 거면 직접 달궈. 나는 빛까지 두드려 봤어.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "솔라펑크",
        "race": "루살카",
        "job": "대장장이",
        "age": "32 세",
        "personality": "예민한",
        "ability": "햇빛에 노출되면 강해지는 능력",
        "weapon": "합성궁",
        "height": "174 cm",
        "weight": "54 kg",
        "measurements": "84 - 58 - 87"
      }
    },
    "folder": "078-naia",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "모이라",
    "en": "Moira",
    "themeColor": "#2910A5",
    "profile": {
      "shortIntro": "도도한 시선에서 광선을 쏘는 마신족 언데드사냥꾼.",
      "quote": "눈을 피하지 마. 사냥감처럼 보이니까.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "궁정물",
        "race": "마신족",
        "job": "언데드사냥꾼",
        "age": "37 세",
        "personality": "도도한",
        "ability": "눈에서 광선을 쏠 수 있는 능력",
        "weapon": "쌍월도",
        "height": "174 cm",
        "weight": "61 kg",
        "measurements": "102 - 58 - 96"
      }
    },
    "folder": "079-moira",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "티스카",
    "en": "Tiska",
    "themeColor": "#883F56",
    "profile": {
      "shortIntro": "우유부단해도 남은 기억을 읽어 끝내 보도하는 사마귀 리포터.",
      "quote": "결정은 늦어도 기록은 정확해야 해요.",
      "basicInfo": {
        "gender": "여성",
        "world": "아스트라",
        "genre": "우주개척물",
        "race": "사마귀 수인",
        "job": "리포터",
        "age": "20 세",
        "personality": "우유부단한",
        "ability": "장소에 남은 기억을 읽을 수 있는 능력",
        "weapon": "전투우산",
        "height": "170 cm",
        "weight": "53 kg",
        "measurements": "83 - 58 - 86"
      }
    },
    "folder": "080-tiska",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "카밀라",
    "en": "Carmilla",
    "themeColor": "#883F56",
    "profile": {
      "shortIntro": "서늘한 미소로 방패를 든 박쥐 수인 마법소녀.",
      "quote": "반짝이는 주문보다, 안 다치게 막는 게 먼저야.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "호러",
        "race": "박쥐 수인",
        "job": "마법소녀",
        "age": "38 세",
        "personality": "서늘한",
        "ability": "알려지지 않음",
        "weapon": "방패",
        "height": "173 cm",
        "weight": "56 kg",
        "measurements": "87 - 58 - 91"
      }
    },
    "folder": "081-carmilla",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "에이다",
    "en": "Ada",
    "themeColor": "#12BB89",
    "profile": {
      "shortIntro": "강철 같은 신념으로 에너지를 방벽으로 바꾸는 오토마톤 학자.",
      "quote": "무너지지 않는 논리라면, 방패로도 쓸 수 있죠.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "밀리터리SF",
        "race": "오토마톤",
        "job": "인공지능학자",
        "age": "없음",
        "personality": "강인한",
        "ability": "에너지를 방어막으로 바꿀 수 있는 능력",
        "weapon": "전기톱",
        "height": "172 cm",
        "weight": "64 kg",
        "measurements": "92 - 58 - 90"
      }
    },
    "folder": "082-ada",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "시요",
    "en": "Siyo",
    "themeColor": "#478DE6",
    "profile": {
      "shortIntro": "소심하게 부적을 붙이고 식신을 부르는 드라이어드.",
      "quote": "제가 나서기엔 무서우니까… 대신 이 아이가 갈 거예요.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "소드앤소서러",
        "race": "드라이어드",
        "job": "식신술사",
        "age": "21 세",
        "personality": "소심한",
        "ability": "알려지지 않음",
        "weapon": "장궁",
        "height": "165 cm",
        "weight": "49 kg",
        "measurements": "84 - 56 - 87"
      }
    },
    "folder": "083-siyo",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "샤드",
    "en": "Shard",
    "themeColor": "#259FCD",
    "profile": {
      "shortIntro": "불안한 숨을 감추고 투명해지는 인형 생존자.",
      "quote": "보이지 않으면 괜찮을 줄 알았는데, 심장은 더 시끄러워.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "좀비 아포칼립스",
        "race": "구체관절인형",
        "job": "생존자",
        "age": "없음",
        "personality": "불안한",
        "ability": "몸을 투명하게 만들 수 있는 능력",
        "weapon": "파워피스트",
        "height": "168 cm",
        "weight": "48 kg",
        "measurements": "78 - 55 - 82"
      }
    },
    "folder": "084-shard",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "노바",
    "en": "Nova",
    "themeColor": "#E64B4F",
    "profile": {
      "shortIntro": "빛을 먹어 힘으로 바꾸는 고요한 골렘 로봇공학자.",
      "quote": "조용히 충전 중이다. 방해하면 출력이 올라간다.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "아톰펑크",
        "race": "골렘",
        "job": "로봇공학자",
        "age": "22 세",
        "personality": "고요한",
        "ability": "자신에게 닿은 빛을 흡수해 힘으로 바꾸는 능력",
        "weapon": "볼라",
        "height": "170 cm",
        "weight": "59 kg",
        "measurements": "88 - 57 - 90"
      }
    },
    "folder": "085-nova",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "포코",
    "en": "Poko",
    "themeColor": "#751999",
    "profile": {
      "shortIntro": "질투심을 어둠에 숨기고 방패를 드는 너구리 대학생.",
      "quote": "나도 할 수 있어. 안 보일 때 더 잘할 뿐이야.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "사이버펑크",
        "race": "너구리 수인",
        "job": "대학생",
        "age": "22 세",
        "personality": "질투심 많은",
        "ability": "어두운 곳에서 기척을 지울 수 있는 능력",
        "weapon": "방패",
        "height": "158 cm",
        "weight": "46 kg",
        "measurements": "78 - 56 - 82"
      }
    },
    "folder": "086-poko",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "시아",
    "en": "Sia",
    "themeColor": "#1CF2AF",
    "profile": {
      "shortIntro": "책임감으로 냉기를 다루는 캇파 현자.",
      "quote": "서두르지 마. 얼어붙은 발걸음도 생각할 시간은 벌어 줘.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "범죄물",
        "race": "캇파",
        "job": "현자",
        "age": "32 세",
        "personality": "책임감 강한",
        "ability": "상대의 움직임을 냉기로 둔하게 만드는 능력",
        "weapon": "권총",
        "height": "168 cm",
        "weight": "54 kg",
        "measurements": "84 - 59 - 88"
      }
    },
    "folder": "087-sia",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "율",
    "en": "Yul",
    "themeColor": "#399839",
    "profile": {
      "shortIntro": "논리로 금지를 정하고 주술검으로 어기는 길을 막는 강시 용병.",
      "quote": "규칙은 간단해. 내가 금지하면, 너는 못 한다.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "로우 판타지",
        "race": "강시",
        "job": "용병",
        "age": "39 세",
        "personality": "논리적인",
        "ability": "자신이 정한 금지 행동을 상대가 하지 못하게 하는 능력",
        "weapon": "주술검",
        "height": "169 cm",
        "weight": "49 kg",
        "measurements": "78 - 55 - 84"
      }
    },
    "folder": "088-yul",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "엘리시아",
    "en": "Elysia",
    "themeColor": "#435624",
    "profile": {
      "shortIntro": "상냥한 미소로 체력이 바닥날수록 더 빠르게 움직이는 설녀 첩자.",
      "quote": "괜찮아요. 지칠수록 저는 더 빨라지거든요.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "하이 판타지",
        "race": "설녀",
        "job": "첩자",
        "age": "36 세",
        "personality": "상냥한",
        "ability": "체력이 낮아질수록 움직임이 빨라지는 능력",
        "weapon": "검",
        "height": "168 cm",
        "weight": "52 kg",
        "measurements": "84 - 58 - 86"
      }
    },
    "folder": "089-elysia",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "리아",
    "en": "Lia",
    "themeColor": "#953E16",
    "profile": {
      "shortIntro": "부지런한 손으로 말을 현실에 잠시 고정하는 오니 기술자.",
      "quote": "말조심해. 내 앞에서는 농담도 잠깐 살아나니까.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "오컬트",
        "race": "오니",
        "job": "마도공학자",
        "age": "25 세",
        "personality": "부지런한",
        "ability": "말한 내용을 잠시 현실로 만들 수 있는 능력",
        "weapon": "암살검",
        "height": "174 cm",
        "weight": "62 kg",
        "measurements": "103 - 58 - 97"
      }
    },
    "folder": "090-lia",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "움브라",
    "en": "Umbra",
    "themeColor": "#893FE2",
    "profile": {
      "shortIntro": "우울한 눈으로 암기를 숨긴 문엘프 교도관.",
      "quote": "탈출로를 찾는 건 자유야. 돌아오는 길은 내가 막을게.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "법정물",
        "race": "문엘프",
        "job": "교도관",
        "age": "35 세",
        "personality": "우울한",
        "ability": "알려지지 않음",
        "weapon": "암기",
        "height": "172 cm",
        "weight": "58 kg",
        "measurements": "94 - 63 - 96"
      }
    },
    "folder": "091-umbra",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "오피시나",
    "en": "Officina",
    "themeColor": "#B51594",
    "profile": {
      "shortIntro": "조심스러운 손끝에 작은 불꽃을 피우는 만드라고라 사냥꾼.",
      "quote": "크게 태우지 않을게요. 필요한 만큼만 뜨겁게.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "이세계",
        "race": "만드라고라",
        "job": "요괴사냥꾼",
        "age": "32 세",
        "personality": "조심스러운",
        "ability": "손끝에서 불꽃을 만들어낼 수 있는 능력",
        "weapon": "방울",
        "height": "167 cm",
        "weight": "52 kg",
        "measurements": "94 - 57 - 89"
      }
    },
    "folder": "092-officina",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "이슬라",
    "en": "Yslra",
    "themeColor": "#803A7E",
    "profile": {
      "shortIntro": "길어진 싸움 속에서 약점을 찾아내는 결단력 있는 마인 사냥꾼.",
      "quote": "오래 버텨 봐. 그러면 네 빈틈도 오래 보이니까.",
      "basicInfo": {
        "gender": "여성",
        "world": "게이트폴",
        "genre": "설원판타지",
        "race": "마인",
        "job": "몬스터헌터",
        "age": "33 세",
        "personality": "결단력 있는",
        "ability": "싸움이 길어질수록 상대의 약점을 파악하는 능력",
        "weapon": "파워피스트",
        "height": "172 cm",
        "weight": "58 kg",
        "measurements": "101 - 58 - 93"
      }
    },
    "folder": "093-yslra",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "카스티엘라",
    "en": "Castiella",
    "themeColor": "#8AE087",
    "profile": {
      "shortIntro": "자상한 손길로 인형과 검을 함께 움직이는 타천사.",
      "quote": "망가진 날개라도 누군가를 안아 줄 수는 있어.",
      "basicInfo": {
        "gender": "여성",
        "world": "사프란해",
        "genre": "해양판타지",
        "race": "타천사",
        "job": "인형술사",
        "age": "39 세",
        "personality": "자상한",
        "ability": "알려지지 않음",
        "weapon": "검",
        "height": "169 cm",
        "weight": "52 kg",
        "measurements": "83 - 58 - 88"
      }
    },
    "folder": "094-castiella",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "키마에라",
    "en": "Kymayra",
    "themeColor": "#A0B6D4",
    "profile": {
      "shortIntro": "집착적인 용기로 짐승의 힘을 빌리는 인간 소방관.",
      "quote": "불길 속에서는 사람답게보다, 살아남게 움직여야 해.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "밀리터리SF",
        "race": "인간",
        "job": "소방관",
        "age": "20 세",
        "personality": "집착적인",
        "ability": "동물의 신체 능력을 잠시 얻을 수 있는 능력",
        "weapon": "독침",
        "height": "168 cm",
        "weight": "54 kg",
        "measurements": "84 - 58 - 88"
      }
    },
    "folder": "095-kymayra",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "토르카",
    "en": "torqa",
    "themeColor": "#025847",
    "profile": {
      "shortIntro": "비밀스러운 웃음으로 화살보다 먼저 길을 지키는 곰 수인 표사.",
      "quote": "짐은 맡겼으면 믿어. 묻지 않는 것도 호위의 일부야.",
      "basicInfo": {
        "gender": "여성",
        "world": "연묵",
        "genre": "무협",
        "race": "곰 수인",
        "job": "표사",
        "age": "31 세",
        "personality": "비밀스러운",
        "ability": "알려지지 않음",
        "weapon": "활",
        "height": "167 cm",
        "weight": "56 kg",
        "measurements": "90 - 60 - 91"
      }
    },
    "folder": "096-torqa",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "아멜리스",
    "en": "Amelys",
    "themeColor": "#213C55",
    "profile": {
      "shortIntro": "다정한 목소리로 죽은 자와 금속을 달래는 엘프 사령술사.",
      "quote": "무서워하지 마세요. 죽은 이들도 거칠게 깨우면 아파해요.",
      "basicInfo": {
        "gender": "여성",
        "world": "노크트",
        "genre": "설원판타지",
        "race": "엘프",
        "job": "사령술사",
        "age": "32 세",
        "personality": "다정한",
        "ability": "금속을 조종할 수 있는 능력",
        "weapon": "단궁",
        "height": "172 cm",
        "weight": "56 kg",
        "measurements": "92 - 59 - 89"
      }
    },
    "folder": "097-amelys",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "드레드나",
    "en": "Dreadna",
    "themeColor": "#AF7237",
    "profile": {
      "shortIntro": "자상한 말투로 존재감마저 감추는 다크드워프 마왕.",
      "quote": "두려워하지 마. 네가 나를 잊는 순간, 이미 끝난 거니까.",
      "basicInfo": {
        "gender": "여성",
        "world": "에레보스",
        "genre": "신화판타지",
        "race": "다크드워프",
        "job": "마왕",
        "age": "33 세",
        "personality": "자상한",
        "ability": "자신의 존재감을 지울 수 있는 능력",
        "weapon": "단검",
        "height": "142 cm",
        "weight": "47 kg",
        "measurements": "99 - 52 - 88"
      }
    },
    "folder": "098-dreadna",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "자히라",
    "en": "Zahyra",
    "themeColor": "#F72212",
    "profile": {
      "shortIntro": "용감하게 빛을 들고 무너진 곳을 살피는 좀비 탐색자.",
      "quote": "겁나도 들어가야 해. 어둠 속에 사람이 있을지 모르니까.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "중동판타지",
        "race": "좀비",
        "job": "폐허탐색자",
        "age": "23 세",
        "personality": "용감한",
        "ability": "빛을 만들어낼 수 있는 능력",
        "weapon": "장궁",
        "height": "168 cm",
        "weight": "53 kg",
        "measurements": "88 - 58 - 86"
      }
    },
    "folder": "099-zahyra",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "바레타",
    "en": "Barretha",
    "themeColor": "#941F96",
    "profile": {
      "shortIntro": "서늘한 왕족의 시선으로 개틀링건을 드는 거인.",
      "quote": "고개를 들고 말해. 나는 작게 굽히는 법을 모른다.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "디스토피아SF",
        "race": "거인",
        "job": "왕족",
        "age": "99 세",
        "personality": "서늘한",
        "ability": "알려지지 않음",
        "weapon": "개틀링건",
        "height": "740 cm",
        "weight": "5.4 t",
        "measurements": "520 - 390 - 560"
      }
    },
    "folder": "100-barretha",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "묘화",
    "en": "MyoHwa",
    "themeColor": "#8CDCA3",
    "profile": {
      "shortIntro": "어둠 속 빠진 흔적까지 세는 꼼꼼한 여우 수인 사냥꾼.",
      "quote": "안 보인다고 없어진 건 아닙니다. 제가 다시 확인하겠습니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "생존물",
        "race": "여우 수인",
        "job": "요괴사냥꾼",
        "age": "43 세",
        "personality": "꼼꼼한",
        "ability": "어둠으로 상대의 시야를 막을 수 있는 능력",
        "weapon": "낫",
        "height": "176 cm",
        "weight": "62 kg",
        "measurements": "96 - 58 - 94"
      }
    },
    "folder": "101-myohwa",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "아테니아",
    "en": "Athenia",
    "themeColor": "#CA0354",
    "profile": {
      "shortIntro": "빛을 낮춰 별의 경고를 읽는 몽환적인 올빼미 인챈터.",
      "quote": "조용한 어둠 속에서야 별이 남긴 문장이 보입니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "아스트라",
        "genre": "고대문명판타지",
        "race": "올빼미 수인",
        "job": "인챈터",
        "age": "22 세",
        "personality": "몽환적인",
        "ability": "어둠을 만들어낼 수 있는 능력",
        "weapon": "전기 채찍",
        "height": "168 cm",
        "weight": "58 kg",
        "measurements": "96 - 58 - 91"
      }
    },
    "folder": "102-athenia",
    "albumKeys": [
      "figure",
      "magazine",
      "sketch",
      "school"
    ]
  },
  {
    "name": "실렉스",
    "en": "Silex",
    "themeColor": "#D7F2EB",
    "profile": {
      "shortIntro": "고장난 기계 앞에서 먼저 사람을 고르는 사이보그 원소술사.",
      "quote": "멈춰야 산다면, 제 몸부터 고장 내겠습니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "코어벨트",
        "genre": "EMP 아포칼립스",
        "race": "사이보그",
        "job": "원소술사",
        "age": "25 세",
        "personality": "결단력 있는",
        "ability": "주변 전자기기를 망가뜨릴 수 있는 능력",
        "weapon": "창,수정구",
        "height": "168 cm",
        "weight": "60 kg",
        "measurements": "85 - 61 - 90"
      }
    },
    "folder": "103-silex",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "가비아",
    "en": "Gavia",
    "themeColor": "#DB1FEA",
    "profile": {
      "shortIntro": "막힌 문을 부수기 전에 안의 생존자를 묻는 악어 사냥꾼.",
      "quote": "문보다 먼저 확인할 게 있지. 아직 누가 안에 있나?",
      "basicInfo": {
        "gender": "여성",
        "world": "애쉬런",
        "genre": "EMP 아포칼립스",
        "race": "악어 수인",
        "job": "사냥꾼",
        "age": "32 세",
        "personality": "뻔뻔한",
        "ability": "진동으로 물체를 부술 수 있는 능력",
        "weapon": "쌍도끼",
        "height": "178 cm",
        "weight": "58 kg",
        "measurements": "100 - 58 - 94"
      }
    },
    "folder": "104-gavia",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "누벨",
    "en": "Nouvel",
    "themeColor": "#AE6676",
    "profile": {
      "shortIntro": "그린 것을 현실로 남기며 책임을 배우는 조용한 만화가.",
      "quote": "그린 장면은 사라지지 않아요. 그러니까 끝까지 봐야 해요.",
      "basicInfo": {
        "gender": "여성",
        "world": "루미아",
        "genre": "미래",
        "race": "인간",
        "job": "만화가",
        "age": "26 세",
        "personality": "얌전한",
        "ability": "그림을 실체화 할 수 있는 능력",
        "weapon": "투척카드",
        "height": "163 cm",
        "weight": "48 kg",
        "measurements": "82 - 56 - 84"
      }
    },
    "folder": "105-nouvel",
    "albumKeys": [
      "magazine",
      "sketch",
      "cookmag"
    ]
  },
  {
    "name": "제니트",
    "en": "Zenith",
    "themeColor": "#7C5CB1",
    "profile": {
      "shortIntro": "전광처럼 비 오는 골목을 가르는 초연한 언데드 사냥꾼.",
      "quote": "죽은 척하는 진실이 제일 빠르게 도망칩니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "오컬트",
        "race": "표범 수인",
        "job": "언데드사냥꾼",
        "age": "25 세",
        "personality": "초연한",
        "ability": "전기를 이용해 빠르게 움직일 수 있는 능력",
        "weapon": "수류탄",
        "height": "170 cm",
        "weight": "53 kg",
        "measurements": "81 - 57 - 87"
      }
    },
    "folder": "106-zenith",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "오르솔라",
    "en": "Ursola",
    "themeColor": "#6ECDAC",
    "profile": {
      "shortIntro": "붙잡은 욕심의 무게를 아는 문어 수인 기사.",
      "quote": "욕심은 숨기지 않겠습니다. 대신 놓치지도 않겠습니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "사프란해",
        "genre": "하이 판타지",
        "race": "문어 수인",
        "job": "기사",
        "age": "39 세",
        "personality": "욕심 많은",
        "ability": "자신의 그림자로 상대를 붙잡을 수 있는 능력",
        "weapon": "갈고리",
        "height": "176 cm",
        "weight": "71 kg",
        "measurements": "106 - 68 - 112"
      }
    },
    "folder": "107-ursola",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "미라벨",
    "en": "Mirabel",
    "themeColor": "#962EE1",
    "profile": {
      "shortIntro": "말보다 남은 진동을 믿는 내성적인 구울 형사.",
      "quote": "저는 사람보다, 떠난 뒤에 남은 무게를 더 잘 봅니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "미드레인",
        "genre": "다크판타지",
        "race": "구울",
        "job": "형사",
        "age": "29 세",
        "personality": "내성적인",
        "ability": "땅의 진동으로 주변 움직임을 감지하는 능력",
        "weapon": "검",
        "height": "167 cm",
        "weight": "55 kg",
        "measurements": "93 - 59 - 90"
      }
    },
    "folder": "108-mirabel",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "베스퍼",
    "en": "Vesper",
    "themeColor": "#656795",
    "profile": {
      "shortIntro": "죽은 자의 힘을 빌릴 때마다 빚을 세는 우울한 퇴마사.",
      "quote": "빌린 힘입니다. 그러니 반드시 갚아야 합니다.",
      "basicInfo": {
        "gender": "여성",
        "world": "에레보스",
        "genre": "호러",
        "race": "엘프",
        "job": "퇴마사",
        "age": "27 세",
        "personality": "우울한",
        "ability": "죽은 자의 힘을 잠시 빌릴 수 있는 능력",
        "weapon": "머신 피스톨",
        "height": "168 cm",
        "weight": "51 kg",
        "measurements": "84 - 58 - 87"
      }
    },
    "folder": "109-vesper",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "벨로아",
    "en": "Velour",
    "themeColor": "#B4833F",
    "profile": {
      "shortIntro": "부서진 로봇보다 살아 있는 사람을 먼저 고치는 공학자.",
      "quote": "기계는 다시 만들 수 있어요. 사람은 부품번호가 없잖아요.",
      "basicInfo": {
        "gender": "여자",
        "world": "코어벨트",
        "genre": "메카물",
        "race": "토끼 수인",
        "job": "로봇공학자",
        "age": "24 세",
        "personality": "강인한",
        "ability": "돌풍으로 상대를 밀어낼 수 있는 능력",
        "weapon": "유탄발사기",
        "height": "173 cm",
        "weight": "59 kg",
        "measurements": "92 - 61 - 93"
      }
    },
    "folder": "110-velour",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "아나크리스",
    "en": "Anachris",
    "themeColor": "#09F2A0",
    "profile": {
      "shortIntro": "같은 하루를 반복하며 실패를 길들이는 켄타우로스 조련사.",
      "quote": "제가 이기적이라서, 같은 죽음은 두 번 못 보겠습니다.",
      "basicInfo": {
        "gender": "여자",
        "world": "아스트라",
        "genre": "신화판타지",
        "race": "켄타우로스",
        "job": "조련사",
        "age": "24 세",
        "personality": "이기적인",
        "ability": "같은 하루를 반복할 수 있는 능력",
        "weapon": "일본도",
        "height": "220 cm",
        "weight": "520 kg",
        "measurements": "88 - 61 - 90\n(접합부 기준)"
      }
    },
    "folder": "111-anachris",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "련",
    "en": "Ryeon",
    "themeColor": "#1F8F28",
    "profile": {
      "shortIntro": "말하지 않은 사연도 식기 전에 곁에 두는 수줍은 바리스타.",
      "quote": "말씀 안 하셔도 괜찮아요. 따뜻한 건 여기 둘게요.",
      "basicInfo": {
        "gender": "여자",
        "world": "루미아",
        "genre": "현대",
        "race": "엘프",
        "job": "바리스타",
        "age": "31 세",
        "personality": "수줍은",
        "ability": "알려지지 않음",
        "weapon": "클로",
        "height": "166 cm",
        "weight": "51 kg",
        "measurements": "82 - 60 - 86"
      }
    },
    "folder": "112-ryeon",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "릭시아",
    "en": "Lixia",
    "themeColor": "#71F7F4",
    "profile": {
      "shortIntro": "무서워도 먼저 빛을 보내 길을 세우는 엔트 결계사.",
      "quote": "제가 앞에 서긴 무섭습니다. 그래서 빛을 먼저 보냅니다.",
      "basicInfo": {
        "gender": "여자",
        "world": "게이트폴",
        "genre": "괴수물",
        "race": "엔트",
        "job": "결계사",
        "age": "25 세",
        "personality": "소심한",
        "ability": "빛으로 만든 분신을 만들어낼 수 있는 능력",
        "weapon": "단검",
        "height": "164 cm",
        "weight": "48 kg",
        "measurements": "80 - 58 - 86"
      }
    },
    "folder": "113-lixia",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "이브리스",
    "en": "Yvris",
    "themeColor": "#C75A72",
    "profile": {
      "shortIntro": "얼어붙은 무도회 뒤에서도 리듬을 잃지 않는 벌 수인 댄서.",
      "quote": "조용히 추어도 됩니다. 얼음도 박자는 남기니까요.",
      "basicInfo": {
        "gender": "여자",
        "world": "사프란해",
        "genre": "스팀펑크",
        "race": "벌 수인",
        "job": "댄서",
        "age": "35 세",
        "personality": "내성적인",
        "ability": "차가운 입김을 불 수 있는 능력",
        "weapon": "마체테",
        "height": "165 cm",
        "weight": "53 kg",
        "measurements": "82 - 59 - 87"
      }
    },
    "folder": "114-yvris",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "휘소",
    "en": "Hwiso",
    "themeColor": "#1C5CF8",
    "profile": {
      "shortIntro": "무너지는 무대 뒤를 먼저 받치는 꼼꼼한 골렘 매니저.",
      "quote": "무너지는 건 제가 받겠습니다. 일정은 그 다음입니다.",
      "basicInfo": {
        "gender": "여자",
        "world": "루미아",
        "genre": "현대 드라마",
        "race": "골렘",
        "job": "매니저",
        "age": "30 세",
        "personality": "꼼꼼한",
        "ability": "알려지지 않음",
        "weapon": "비녀검",
        "height": "168 cm",
        "weight": "55 kg",
        "measurements": "88 - 61 - 91"
      }
    },
    "folder": "115-hwiso",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "릭스",
    "en": "Ryx",
    "themeColor": "#8CA8B0",
    "profile": {
      "shortIntro": "들키면 함께 삼켜지는 문을 숨기는 용인 결계사.",
      "quote": "숨기는 건 배신이 아닙니다. 아직 닫히지 않은 문입니다.",
      "basicInfo": {
        "gender": "여자",
        "world": "에레보스",
        "genre": "코즈믹 호러",
        "race": "용인",
        "job": "결계사",
        "age": "23 세",
        "personality": "비밀스러운",
        "ability": "그림자로 변신할 수 있는 능력",
        "weapon": "전투삽",
        "height": "167 cm",
        "weight": "58 kg",
        "measurements": "82 - 58 - 86"
      }
    },
    "folder": "116-ryx",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "니르바",
    "en": "Nyrva",
    "themeColor": "#682F86",
    "profile": {
      "shortIntro": "억지로 세워진 죽음의 자리를 드러내는 티플링 사신.",
      "quote": "대신 죽겠다는 게 아닙니다. 누가 세워졌는지 보게 하겠습니다.",
      "basicInfo": {
        "gender": "여자",
        "world": "에레보스",
        "genre": "코즈믹 호러",
        "race": "티플링",
        "job": "사신",
        "age": "22 세",
        "personality": "헌신적인",
        "ability": "자신과 상대의 위치를 바꿀 수 있는 능력",
        "weapon": "플라즈마건",
        "height": "164 cm",
        "weight": "49 kg",
        "measurements": "83 - 58 - 86"
      }
    },
    "folder": "117-nyrva",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "네리사",
    "en": "Nerissa",
    "themeColor": "#17D53E",
    "profile": {
      "shortIntro": "닿지 않는 깃발까지 뛰어오르는 카리스마 있는 정령 해적.",
      "quote": "가벼워지는 건 도망치려고가 아니라, 더 높이 가려고죠.",
      "basicInfo": {
        "gender": "여자",
        "world": "사프란해",
        "genre": "항해물",
        "race": "정령",
        "job": "해적",
        "age": "24 세",
        "personality": "카리스마 있는",
        "ability": "자신의 몸을 가볍게 만들어 높이 뛰는 능력",
        "weapon": "사브르",
        "height": "172 cm",
        "weight": "52 kg",
        "measurements": "88 - 59 - 91"
      }
    },
    "folder": "118-nerissa",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "로엔",
    "en": "Loen",
    "themeColor": "#DC03DC",
    "profile": {
      "shortIntro": "망가지기 전의 떨림까지 살피는 상냥한 여우 수인 메카닉.",
      "quote": "상냥함은 느린 수리가 아니라, 다시 망가지지 않게 보는 거예요.",
      "basicInfo": {
        "gender": "여자",
        "world": "아스트라",
        "genre": "소프트SF",
        "race": "여우 수인",
        "job": "메카닉",
        "age": "21 세",
        "personality": "상냥한",
        "ability": "알려지지 않음",
        "weapon": "레이저 소총",
        "height": "166 cm",
        "weight": "53 kg",
        "measurements": "87 - 58 - 88"
      }
    },
    "folder": "119-loen",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  },
  {
    "name": "신시아",
    "en": "Cynthia",
    "themeColor": "#E2D5C5",
    "profile": {
      "shortIntro": "기적도 무대에 올리기 전 검증하려는 논리적인 가수.",
      "quote": "기적을 믿는 것과 검증하지 않는 건 다른 문제입니다.",
      "basicInfo": {
        "gender": "여자",
        "world": "루미아",
        "genre": "아이돌물",
        "race": "인간",
        "job": "가수",
        "age": "26 세",
        "personality": "논리적인",
        "ability": "알려지지 않음",
        "weapon": "마이크",
        "height": "172 cm",
        "weight": "56 kg",
        "measurements": "92 - 56 - 92"
      }
    },
    "folder": "120-cynthia",
    "albumKeys": [
      "magazine",
      "sketch"
    ]
  }
];
